### ISSUE TITLE
featureCounts with built-in annotations?

### ISSUE THREAD

**Issue by dpryan79** [galaxyproject/tools-iuc#1016]
It would be nice if the IUC featureCounts wrapper could use built-in annotations (presumably from the `gene_sels.loc` table). I'd be happy to try to put together a PR to add this functionality if others also found it useful (it's in the original wrapper from @yhoogstrate, but that doesn't handle dataset collections, while this one does). Thoughts?

**Comment by lparsons** [comment]
Annotations in featureCounts would be very nice (also in DeSeq2). I didn't know about the `gene_sels.loc` table, what tool(s) use it?

**Comment by bgruening** [comment]
:+1:

**Comment by dpryan79** [comment]
@lparsons That should have been `gene_sets.loc`, sorry about the typo. I know the original featureCounts wrapper used the gene_sets table, but aside from that I haven't a clue if anything else does.

**Comment by yhoogstrate** [comment]
I Made the tablet name and structure up myself So it's not according to any standard afaik and probably unique. I did not include it in the featurecounts PR because I thought Nobody else would like to use tables for gtf files (as they update so frequently) but apparently i was wrong. Great initiative @dpryan79
