### ISSUE TITLE
samtools 1.3.1

### ISSUE THREAD

**Issue by Yating-L** [galaxyproject/tools-iuc#1025]
The job command line :"samtools sort" not work for version 1.2. It works for 1.3. It might need to update your tool dependency, samtools to 1.3.1

**Comment by yhoogstrate** [comment]
I wanted to test this but the bioconda build of samtools 1.2 did not let me do this because linking with ncurses on Arch is broken. The current build of 1.2 was built on the old build system and is incorrectly linked to the system build of ncurses. This problem shall appear more often  in the future as distros shall update their ncurses.

The 1.2 directory is not present as bioconda-recipe anymore. I will try to recover this for the sake of reproducibility.

**Comment by yhoogstrate** [comment]
There is indeed weird behaviour in arg-parsing of samtools 1.2. It feels like it starts parsing from arg[2] instread of arg[1]. You could get it back working again by running `samtools sort -f unsorted.bam sorted.bam`. Anyway, I believe this affects *./tools/bedtools/bamToBed.xml* when the `-bedpe` option is selected. In hisat it seems to work properly. Trinity I can't confirm because it's an internal tool dependency, but it has passed the travis test. BWAMETH may be affected. BCFtools does not use `sort` but `mpileup`. JBrowse may be affected but I can't confirm this either because it's an internal tool dependency.

**Comment by Yating-L** [comment]
I start a new Ubuntu VM and it worked well. I was using my Mac earlier. I think it might get messed up because I have installed samtools 1.3.1 on my Mac. Or it might just because the tool only work on Linux? Thank you!

**Comment by yhoogstrate** [comment]
Hi @Yating-L ,

As long we have no obvious iuc tool that crashes because of this, I don't see a reason to keep this open. Samtools 1.2 is used as dependency not only for sorting. If you do find a galaxy tool that suffers from this issue, please re-open or submit a new issue. I am glad you reported it and let's pray nothing is really affected after all. If you have any reason to still leave this open, please ask. Thanks for reporting the issue. Have a nice weekend,

Youri
