### ISSUE TITLE
Setting up TravisCI continuous integration for IUC tools

### ISSUE THREAD

**Issue by peterjc** [galaxyproject/tools-iuc#11]
Suggested by @bgruening, it would be great to have the IUC tools tested automatically using TravisCI.

Note that my setup described here http://blastedbio.blogspot.jp/2013/09/using-travis-ci-for-testing-galaxy-tools.html as used on https://github.com/peterjc/galaxy_blast and https://github.com/peterjc/pico_galaxy does not use the Tool Shed packages - it "manually" installs the dependencies from source or using "apt-get install".

What would be ideal for the IUC tools (and my own tools in the long term) would be to have the TravisCI script setup a local Galaxy and a local Tool Shed, and use this to test our IUC packages as well.

**Comment by erasche** [comment]
https://github.com/galaxyproject/planemo/issues/15 is also relevant. That coupled with the docker-in-travis described above and we'd be almost there.

**Comment by erasche** [comment]
Additionally, if we're using planemo for that...we should be deploying to the toolshed when PRs are merged into master. :D

**Comment by erasche** [comment]
Okay y'all, I'm tired of seeing this issue, so....I set up [jenkins testing](http://gx.hx42.org) in the meantime to test ALL of the tools. Yes it's overkill, but it's *something*, and it's working now until someone sets up Travis testing.

- The planemo and galaxy updater jobs can be run to keep them up to date (they're global, let's just test against latest, if anyone *really* cares that much, we can do matrix testing later.)
- Configure jobs to run as regularly as y'all like, beware that the current tools suite testing takes ~40 minutes.
- Brew is available, if you need to install tools just create a job and add "brew install" steps as shell commands
- The Jenkins admin user is "iuc" with the same credentials as the IUC account on the toolshed. 
    - There's also a local user with the same username/password and sudo privileges for installing debian packages.
- I'm vaguely considering using [shed2tap](https://github.com/jmchilton/shed2tap) and brew to install the `tool_dependencies.xml` globally. It'd be nice for planemo to implement that eventually, but this would provider a short term solution.

Currently, two things (mostly) pass:

- seqtk
- bedtools

The rest I was too lazy to dig into tool_dependencies and actually install the backend packages, someone may want to do that....

**Comment by erasche** [comment]
Jenkins testing is now live and working. My apologies for all of you who got emails because the bot auto-commented on all open issues requesting an admin to verify a patch. I've removed or altered those comments to instruct jenkins to test where appropriate.

So, on to the neat stuff:

- To test (I'm pretty sure all IUC members are on the list) just comment with "please test this", and that should trigger jenkins to test it if it hasn't already. It'll be a bit of a learning experience for us all :)
- There are some other "keyword phrases", but I don't know what to do with most of them, so I'm not going to worry about them. If there's anyone here who is really knowledgeable about this particular jenkins plugin and likes figuring out delegation of build permissions, then have at it. 
- I'm going to add a job to push to the TTS soon for successfully built packages.

**Comment by erasche** [comment]
I'm going to see if I can build a jenkins plugin for galaxy tool testing. If I can, I'm willing to open this up as a free service to anyone above a threshold of some # of tools/packages. If that continues to work well, I'll further open the jenkins instance up to anyone who wants to use it for testing + deploying Galaxy tools.

If anyone cares about travis, please feel free to work on that and I'll quit with Jenkins.

As I see it, Pros of Jenkins vs Travis:

- Builds/outputs/etc can be archived
- Planemo HTML reports can be made visible from each build
- Docker can be used easily (no tricks needed like mentioned above, I don't know if that's changed)

Cons of Jenkins vs Travis:

- Travis is free
- With encrypted env vars, you can use planemo to push as your own user (maybe there's a jenkins plugin for this though?)

Neutral(ish) Items:

- both will support us using planemo to push to TSs. With jenkins I'd probably use dedicated TS user (rather than the IUC account like I do now).

**Comment by yhoogstrate** [comment]
@jmchilton @erasche @bgruening @nsoranzo @peterjc Thanks for making this happen :+1:

**Comment by bgruening** [comment]
Reading this again, shows that we have gone a long way! Thanks a bunch to the entire Galaxy community to make all this happen what was required to get this issue done!
