### ISSUE TITLE
IUC meeting at GCC 2017

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#1369]
Potential topics to discuss:

* https://github.com/galaxyproject/tools-iuc/issues/1262
* https://github.com/galaxy-iuc/standards/pulls
* tool describing tours and potential impact to our standards
* newest developments around Conda and Containers (dropping `r`-channel, Singularity, ...)
* automatic update of tools?
* clarify when to use explicit collection input and output

Proposed date/time: Wednesday 2017-06-28 evening

**Comment by gregvonkuster** [comment]
How about getting consensus on the following related topics

- https://github.com/galaxyproject/tools-iuc/pull/1227 - Conversation regarding Enhance MultiGPS to handle multiple inputs

- https://github.com/galaxyproject/tools-iuc/issues/1230 - Important but not "best practice" tools?

- https://github.com/galaxyproject/tools-iuc/issues/1285 - Process for handling tools that fail travis tests or cannot be automatically tested

**Comment by nsoranzo** [comment]
@erasche took some notes, I can add the list of people that participated:
- erasche
- shiltemann
- nsoranzo
- mvdbeek
- bgruening
- blankenberg 
- bebatut
- abretaud
- natefoo
- jj-umn

Non-IUC members:
- jmchilton
- hmenager
- lecorguille
- martenson

**Comment by martenson** [comment]
@erasche if you provide a photo of the notes I can do the OCR.

**Comment by erasche** [comment]
Ok, thanks for the reminder @martenson.

# IUC meeting 2017-06-28

## Deprecating packages

person  | comment
--- | ---
@nsoranzo | old packages still exist, admins are safe
@mvdbeek | move as stance, no damage to admin
all | implicit support
@jj-umn | <agreement>
@bgruening | step further, warn or prevent when admins try and install non-condafied dependencies?
@blankenberg | what about small / focused things? does bioconda want these?
 | <yes this is fine>
@mvdbeek | How about a warning at 17.09 about this?
@jmchilton | open an issue
@mvdbeek | will do

This passes. From now on, all packages in the IUC repository are officially deprecated. Xref https://github.com/galaxyproject/tools-iuc/issues/1262

## Recommendations on use of `<section />`s in tools

Person | comment
--- | ---
@jj-umn | Use them.
@jmchilton | by being rigid we encourage repro, but make upgrades harder.
@jj-umn | sections have better UX
@nsoranzo | maybe phrase more softly, as a recommendation
@bgruening | is this a deficiency in sections?
@jmchilton | could use tool profiles
@mvdbeek | we still don't enforce those
@bgruening | can we do it in a backwards compatible way? default to true / expanded?
@jmchilton | could not show the section if on old galaxy versions
@blankenberg | well the admin can always just downgrade / uninstall if it isn't working how it used to.

Motion fails, sections will not be recommended as standard practice. We will recommend their use for their improved UX, but due to end-user ambiguity over whether or not the options within the collapsed section are actually used, we cannot recommend them.

## Tool Describing Tours (and impact on standards)

Person | Comment
--- | ---
@bgruening | enhance tests with "help" attribute
@nsoranzo | not called help
@bgruening | mark tests as "tours" or just say first test
@jmchilton | "doc" on param in test, and if the doc param is present, present this as a tour. Also add `name` attribute to test, which will be nice for planemo.
@bgruening | add "doc" to inputs/outputs as well.

less of a motion, more of a discussion topic. General consensus that this is a reasonable idea and a reasonable approach.

## Test Data Size

Person | Comment
--- | ---
@bgruening | increasing test data size, no point in saving the data in github or in the TS (and thus in all of the galaxies that clone that repo). Would like to support URLs instead. 3 goals: bigger files for more accurate tests, saving space, <author-missed>. Mostly driven by the space issue.
@mvdbeek | time drives this too, slow installations are not good. Is this a proxy for "I don't want to narrow down test case"?
@erasche | clarification: only big inputs? not outputs?
@blankenberg | datasets for training
@jmchilton | if we had infra for this users would like it.

conclusion: ???

## Conda / Containers / Drop r-channel / singularity
@bgruening | could just move `r-` to end.
@bgruening | conda build 3 released, easier to pin packages. Bioconda has limited space. Maybe talk about pricing?
@erasche | host our own!
@bgruening | mirror entire channel.
@jmchilton | we need to mirror no matter
@bgruening | singularity images? Do we want to store these?
@jmchilton | devteam, iuc building singularity containers
@bgruening | idea to convert old containers to singularity, also biocontainers
@jmchilton | planemo test tools-iuc in (singularity) containers?
@bgruening | can it happen in easily deployable containers (i.e. docker-galaxy-stable)?
@jmchilton | but startup time?
@mvdbeek | @bgruening solved with database dumps. agree that this is good.

conclusions:
- `r-` to end: yes
- host our own: yes
- ...???

## Automatic Updates

Person | Comment
--- | ---
@bgruening | we can easily have yaml files describing an instance. is it a problem about many versions of some tools installed?
@martenson | surely no one is interested in this
galaxy-admins | yes, we are.
@mvdbeek | yaml file has problem with sections. e.g. text manipulation section, tools get added to a duplicate section.
@martenson | search sucks
@blankenberg | users should be able to config toolbox
@jj-umn | user toolbox profiles.

conclusion: automatic updates should happen. Some fine points to discuss / identify regarding whether or not people are fine with N versions of a tool (most of which are tiny updates / rarely used) installed.

## EDAM Topics

@hmenager | edam topics were defined, willing to help should add to tools iuc / standards#45

## Explicit Collection I/O

Person | Comment
--- | ---
@mvdbeek | never. PR to training material for map/reduce graphic that I have.

## Composite Datatypes + Failing Tests

Person | Comment
--- | --- 
 | some should be supported.
@mvdbeek | hackathon worked on zipped uploads
@jmchilton | add `workflows/` directory, with yaml? workflows. Need support and beta testers.
@bgruening | volunteering to test this.
@mvdbeek | volunteering @pvanheus for zip upload implementation
@mvdbeek | merge without passing test?
@bgruening | @blankenberg please fix testing of data managers. Can you sketch a plan for testing implementation? (I.e. we need this and will work on it, but need some implementation guidance)
@mvdbeek | no, you can do this or <illegible>

## Important, but not Best Practice Tools

Person | Comment
--- | ---
@bgruening | No.
@mvdbeek | cookie-cutter repo.

Conclusion: we will not merge important but non-best practice tools in the interests of keeping IUC tools as a good reference point for beginners.

## Updating of Dependencies

Person | Comment
--- | ---
@jmchilton | Are IUC tools well maintained?
@jmchilton / @martenson / @blankenberg | well maintained = updated versions
@bgruening | bot to PR updates when new conda packages are available?
@natefoo | minor version updates maybe fine?
@jmchilton | @bgruening will write response.


## Hackathons

- tool test documentation 
- workflows
- ... ?

## Security

Person | Comment
--- | ---
@mvdbeek | sanitization of element identifiers needs checking
@erasche |  we merged security stuff, initial group of myself / @jmchilton / @natefoo 
@jmchilton | should be clear about what sanitization of element identifiers will be done. Always on backburner but definitely wanted.

**Comment by martenson** [comment]
for the `Test Data Size` topic I am pretty sure project can provide the infrastructure to host (and distribute) this - similar (same/) to cargo-port.

**Comment by gregvonkuster** [comment]
Thanks for all of the work that went into this discussion and the notes here!  Its very helpful for those of us that could not attend the GCC.

**Comment by gregvonkuster** [comment]
From this conclusion...

> Conclusion: we will not merge important but non-best practice tools in the interests of keeping IUC tools as a good reference point for beginners.

...it seems that I should close this PR https://github.com/galaxyproject/tools-iuc/pull/1227 and deprecate the tool in the TTS/MTS since it is currently owned by ```iuc``` and the current test framework for the ```tools-iuc``` repo do not test against a Galaxy environment that has chromosome length files installed.  I'll move it to my ```galaxy_tools``` repo and upload it to the TTS/MTS with owner ```greg```.

**Comment by mvdbeek** [comment]
Don't worry @gregvonkuster, this is on my todo list, and since the tool is in already it's OK to stay (IMHO).

**Comment by gregvonkuster** [comment]
Ok, thanks!  I'll leave things for now, but I'm happy to move it if that is best.
