### ISSUE TITLE
query_tabular - feature request (or discussion)

### ISSUE THREAD

**Issue by eschen42** [galaxyproject/tools-iuc#1428]
I have a two-part feature request for `query_tabular`, assuming that it seems reasonable to you.

As a simple example, I have a TSV file similar to the following:

| sampleMetadata | class | polarity |
| :--- | :--- | :--- |
| blank\_211 | blank | unknown |
| blank\_215 | blank | unknown |
| blank\_218 | blank | unknown |
| blank\_223 | blank | unknown |
| blank\_226 | blank | unknown |
| pool\_210 | pool | unknown |
| pool\_214 | pool | unknown |
| pool\_219 | pool | unknown |
| pool\_222 | pool | unknown |
| Y10\_212 | y0 | unknown |
| Y10\_213 | y0 | unknown |
| Y10\_216 | y0 | unknown |
| Y20\_217 | y0 | unknown |
| Y20\_220 | y0 | unknown |
| Y20\_224 | y0 | unknown |
| Y20\_225 | y0 | unknown |

To do so, I run `query_tabular` using the following \(somewhat contrived\) parameters to select the blank rows:

| Input Parameter | Value |
| :--- | :--- |
| **workdb** | workdb.sqlite |
| **add\_to\_database** | |
| * Add tables to this Database | |
| * Tabular Dataset for Table | 3: sampleMetadata.tsv |
| *input\_opts:* | |
| * Filter By | skip |
| Skip lines | 1 |
| *tbl\_opts:* | |
| * Specify Name for Table | sampleMetadata |
| * Specify Column Names \(comma-separated list\) | sampleMetadata,class,polarity |
| * Only load the columns you have named into database | False |
| * Add an auto increment primary key column with this name | Empty. |
| * This is a unique index | True |
| * Index on Columns | sampleMetadata |
| **Save the sqlite database in your history** | False |
| **SQL Query to generate tabular output** | select \* from sampleMetadata where sampleMetadata like 'blank\_%' |
| **Omit column headers from tabular output** | False |

My output looks like this:

| #sampleMetadata | class | polarity |
| :--- | :--- | :--- |
| blank\_211 | blank | unknown |
| blank\_215 | blank | unknown |
| blank\_218 | blank | unknown |
| blank\_223 | blank | unknown |
| blank\_226 | blank | unknown |

There are two options that I would have:

1. My output table has a pound sign prepended to the name of the first colum, and I need to use the sed\_wrapper tool to get rid of it.
  * **It would be nice to have an option to suppress the generation of this # character to save a workflow step.**
2. The names for the columns are already present in the first line, but I have to specify them explicitly in the parameter "Specify Column Names \(comma-separated list\)".
  * **It would be nice to have an option to extract the column names from the first line.**
  * This is particularly important for workflows where the column names in the input file that I need to use in the SQL query are unchanging but the column numbers where they appear may change, depending on how previous tools have manipulated columns in the file. \(For example, Workflow4Metabolomics tools add columns to sampleMetadata and variableMetadata in the course of a workflow.\)
   * I am assuming here that some sanity-checking for valid names, or synthesis of valid names, might be necessary for column names that are not valid SQL field names.

**Comment by bgruening** [comment]
@eschen42 thanks for your suggestions! Let ask our SQL master @jj-umn if this would be easy to implement.

**Comment by jj-umn** [comment]
@eschen42 @jennaj
1. It would be nice to have an option to suppress the generation of this # character to save a workflow step.

This will be easy to do.  I'll just add a boolean param to do that.  Should I do that immediately?

2. The names for the columns are already present in the first line, but I have to specify them explicitly in the parameter "Specify Column Names (comma-separated list)".  It would be nice to have an option to extract the column names from the first line.

I had avoided this before because the files I was working with had lots of column headings that would need to be quoted or altered to be used as file names, and it was easier for me to list may own names.  But I'll see how I can add this feature now.  The user would need to leave the column headings during the input file filtering.  We might need to add the option to name any added column.  
The column header line would be read as column names when the table is going to be created.  Do we need to consider multiline line column headers?   I'd have to check if that can be quoted away.
[https://sqlite.org/lang_keywords.html](https://sqlite.org/lang_keywords.html)  
We need to consider whether to have the user select the quoting style, or whether to have an ordered preference for applying them based on the header string.  The help section will need to be updated to explain the naming procedure.

**Comment by jj-umn** [comment]
@eschen42  [https://github.com/galaxyproject/tools-iuc/tree/query_tabular_1428](https://github.com/galaxyproject/tools-iuc/tree/query_tabular_1428)  has code for this.  
I haven't made a pull request as yet.  Can you take a look and see if this does what you want?  
Also, let me know if you have any test cases that you want me to try.
