### ISSUE TITLE
FeatureCounts 1.6.0.2 has the first "built-in" Gene annotation file auto-selected. Would avoid usage errors to require active selection. 

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#1754]
**Tool**: featureCounts Measure gene expression in RNA-Seq experiments from SAM or BAM files. (Galaxy Version 1.6.0.2)

Users do not always notice when an option is pre-filled on a tool form.

I can select an input with the database metadata set as "mm10" but still have a form filled out with "hg38", the first index available, selected.

Enhancement ideas to avoid usage problems:

 - **Force users to actively choose a built-in annotation file**. Meaning, the default on the tool form would be blank or "unspecified (?)". 
 - **If nothing is chosen, do NOT submit the job**, but give a warning on the tool form that a selection must be made (built-in or from the history).
 - We could **use the input database metadata to auto-select annotation, if the input database matches one of the built-in indexes**. Nice to have, but is a niche use-case if there are only 4 indexed annotations available. 
 - AND, **IF there is a mismatch between the input datatype assignment and the built-in annotation selected (not for history annotation), also do not submit the job**, instead, warn the user at submission that they need to correct the mismatch. Mapping tools always tag the BAM/SAM output with the genome/database used for mapping -- unless a custom genome is used, which would not use one of the built-in annotations anyway.

Many existing tools do one of the above. It avoids very common usage errors -often users do not even notice the problem until some downstream tool errors or produces odd results. This is frustrating after doing the heavy lifting of getting through many mapping jobs + intermediate tools that might not fail but produce odd but unnoticed results. All jobs have to be rerun from the start when the wrong built-in index is used.

We are considering doing the same for more tools (mapping tools as a priority https://github.com/galaxyproject/galaxy/issues/4499) that have still built-in indexes auto-selected. **These are passively and randomly "selected"** - what is used is just the first in the index list on that server. Instead, tools should require actively-selected built-in indexes/genomes at runtime or data mismatch problems result.

Discussion welcome - just trying to make things easier for our end-users. Alternative ideas/solutions are great.

**Comment by bgruening** [comment]
On the tool side we could make use of more validators and check for the dbkey more often. But this requires that the user actively annotates all datasets with the dbkey. 
A fix on the Galaxy side could be to not select anything if the select box is filled from a location file.

ping @blankenberg @guerler

**Comment by mblue9** [comment]
Hi @jennaj thanks a lot for reporting this!! And sorry, I was the one who added the built-in annotation recently. As a start towards fixing this I've made the GTF the default selection (instead of the built-in annotation) in the PR here: https://github.com/galaxyproject/tools-iuc/pull/1755 but if I should make more changes please let me know!

**Comment by blankenberg** [comment]
I think a preference on filters and then validators are the way to go. We shouldn't let things be selected that can't be run, and we shouldn't run things that are wrong. Probably some enhancement work needed to get this really working correctly, especially in the case of grouping constructs.

As far as the dbkey is concerned, I think we should be training and requiring users to have matching keys, otherwise very strange/wrong results can happen. Likely allowing '?' to match with '?' will prevent concerns about custom datasets that a user hasn't created a custom genome for.

Perhaps during file upload, we can make it much more obvious in the GUI that a user should set a dbkey on their files. Bold, blinking, and red? Maybe a popup tooltip that gives a warning? Maybe have it dismissable by a user with memory, and only have it appear when its likely needed: for example genomic regions should have a dbkey set, fastq files shouldn't.

**Comment by mblue9** [comment]
> Probably some enhancement work needed to get this really working correctly, especially in the case of grouping constructs.

Does this mean more enhancement could be made to the featurecounts wrapper? I made some guesses at what to change (in the PR here: https://github.com/galaxyproject/tools-iuc/pull/1755) but if there are others changes I could/should make please let me know.

>As far as the dbkey is concerned, I think we should be training and requiring users to have matching keys

Great idea! As one thing I was wondering is... what happens if a user uploads a load of BAMs (like 50), doesn't set the genome, and then goes to try to run featurecounts using e.g. the built-in hg38. Would they have to edit the dbkey on every file one-by-one? Or is there a batch operation (non-API) for users for that?

**Comment by jennaj** [comment]
Changing metadata for multiple datasets at once is another enhancement idea that started with one request and had more activity/ideas added by others. https://github.com/galaxyproject/galaxy/issues/3195 Right now the option is either to either edit attributes per-dataset or reload. 

I really like the pop-up "Did you forget to set this?" GUI idea from Dan. 

The tool filter _could_ be constructed so that BAMs with "?" assigned as the database are permitted to select any reference annotation. But make that an active choice still. And if a BAM does have a dbkey assigned, only permit the select if it is a match. This wouldn't be as strict - and is not my favorite solution. 

People map against the wrong database by accident and don't find out until they get odd results or a failure with a downstream tool. Ticket for an enhancement to prevent that is here: https://github.com/galaxyproject/galaxy/issues/4499

Dan might have other ideas about how to model this. If there is are ways to prevent common usage mistakes upfront, I'm all for them.

**Comment by jennaj** [comment]
Featurecounts v 1.6.0.3 test well at htps://usegalaxy.org against all of the usage problems that can come up plus with correct inputs. Thank you!!  Closing.
