### ISSUE TITLE
Error while running crossmap_bam

### ISSUE THREAD

**Issue by bellenger-l** [galaxyproject/tools-iuc#1894]
Hello,

I tried to use crossmap_bam (with a bam file and UCSC chain file downloaded from http://crossmap.sourceforge.net/) and I can't make it work.

I am suspecting an error with pysam, can you please launch again the travis test in order to check if this is an environment issue ?

Best,
Lea

**Comment by nsoranzo** [comment]
@bellenger-l Is the issue you're seeing something like what is at the end of https://travis-ci.org/galaxyproject/tools-iuc/jobs/382626405 ?

**Comment by nsoranzo** [comment]
@bellenger-l The issue was caused by pysam 0.14, which contains a change that breaks CrossMap bam. You can either downgrade pysam to 0.13.0 in the `__crossmap@0.2.5` conda environment or upgrade the Galaxy crossmap tools from the Tool Shed (which should create a new `__crossmap@0.2.7` conda environment with an older pysam).

**Comment by bellenger-l** [comment]
@nsoranzo thank you for your reactivity,

Best,
Lea
