### ISSUE TITLE
Missing downloads

### ISSUE THREAD

**Issue by erasche** [galaxyproject/tools-iuc#212]
# Scope

Since I started this PR the scope has expanded.

- [x] work in #213 
- [x] merging #208 
- [x] ALL SF downloads are broken (uggghhhh SF)
- [ ] Move R packages to MRAN
- [x] Store CPAN packages in the download store

## Other Tasks

Done | Owner | URLs/Packages
--- | --- | ---
 x | @bgruening  | https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_chemfp_1_1/tool_dependencies.xml#L14 doesn't exist
 | @erasche | gclient/gfserver
 x | @erasche | monocle

**Comment by erasche** [comment]
everything in package_gfclient_35x1

**Comment by yhoogstrate** [comment]
https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_monocle_1_0_0/tool_dependencies.xml

**Comment by erasche** [comment]
oh jeez, yeah, no surprise there. Thanks @yhoogstrate

**Comment by erasche** [comment]
(I'm working my way through adding sha256sums to all packages in the IUC repo

**Comment by erasche** [comment]
TODO: switch to https://mran.revolutionanalytics.com/documents/rro/reproducibility/ for standard R package archives. They're mirrors by date. https://mran.revolutionanalytics.com/snapshot/

**Comment by yhoogstrate** [comment]
Maybe we can somehow link this issue to PR https://github.com/galaxyproject/tools-iuc/pull/208 because they both focus on URL checking. Anyway, I found those guys:


packages/package_perl_xml_parser_expat_2_41/tool_dependencies.xml	http://search.cpan.org/CPAN/authors/id/E/ET/ETHER/URI-1.65.tar.gz

packages/package_homer_4_2/tool_dependencies.xml
http://biowhat.ucsd.edu/homer/homer.v4.2.zip

packages/package_r_3_1_1/tool_dependencies.xml
http://depot.galaxyproject.org/package/darwin/x86_64/R/R-3.1.1-Darwin-x86_64.tgz

packages/package_cd_hit_auxtools_0_5_2012_03_07_fix_dan/tool_dependencies.xml
http://depot.galaxyproject.org/package/linux/x86_64/cd-hit-auxtools/cd-hit-auxtools-0.5-2012-03-07-fix-dan-gh-0.0.1-Linux-x86_64.tgz

packages/package_cd_hit_auxtools_0_5_2012_03_07_fix_dan/tool_dependencies.xml
http://depot.galaxyproject.org/package/linux/i386/cd-hit-auxtools/cd-hit-auxtools-0.5-2012-03-07-fix-dan-gh-0.0.1-Linux-i686.tgz

packages/package_cd_hit_auxtools_0_5_2012_03_07_fix_dan/tool_dependencies.xml
http://depot.galaxyproject.org/package/darwin/x86_64/cd-hit-auxtools/cd-hit-auxtools-0.5-2012-03-07-fix-dan-gh-0.0.1-Darwin-x86_64.tgz

packages/package_rnashapes_2_1_6/tool_dependencies.xml (most of them)

packages/package_chemfp_1_1/tool_dependencies.xml
http://share.gruenings.eu/simsearch.py

**Comment by erasche** [comment]
@yhoogstrate yes, definitely. Sorry, didn't notice that that was still open. Will get that merged.

**Comment by yhoogstrate** [comment]
I want them to be automatically tested by planemo first. Is that already possible via github or should I do it manually?

**Comment by erasche** [comment]
automatically tested? Like complete package installation?

**Comment by yhoogstrate** [comment]
Yep.. if that's possible?

**Comment by erasche** [comment]
It should be? You might create a temporary toolshed, and then run this: http://planemo.readthedocs.org/en/latest/commands.html#shed-test-command

**Comment by erasche** [comment]
There should be a docker galaxy toolshed around somewhere by the way. If you get a command worked out, we'll add it as part of the test procedure.

**Comment by erasche** [comment]
@yhoogstrate do you mind if I merge your URL PR into this one and combine them? I'll also be fixing missing URLs/changing R packages to MRAN which are dated.

**Comment by yhoogstrate** [comment]
Of course I don't mind!

**Comment by erasche** [comment]
xref https://github.com/galaxyproject/planemo/issues/228

**Comment by yhoogstrate** [comment]
@erasche Is this still an open issue?
