### ISSUE TITLE
filter options in tool data table

### ISSUE THREAD

**Issue by davidchristiany** [galaxyproject/tools-iuc#2151]
Hi,

I am trying to filter a tool data table with the <filter> tag.
I want to remove lines which contains a value in a selected column.
I tried this : 

                 `<param name="version" type="select" label="Select version of reference file">`
                    `<options from_data_table="id_mapping_tab">`
                        `<filter type="remove_value" key="id" value="rat_id_mapping_19-10-2018"/>`
                    `</options>`
                `</param>`

My tool data table looks like this : 

    `<table name="id_mapping_tab" comment_char="#">`
        `<columns>id,name,value,path</columns>`
        `<file path="tool-data/id_mapping_tab.loc" />`
    `</table>`

And my data table : 

```
human_id_mapping_19-10-2018    Homo sapiens (19-10-2018)       human_id_mapping        /home/dchristiany/proteore_project/galaxy/tool-data/id_mapping/human_id_mapping_19-10-2018.tsv
rat_id_mapping_19-10-2018       Rattus norvegicus (19-10-2018)  rat_id_mapping  /home/dchristiany/proteore_project/galaxy/tool-data/id_mapping/rat_id_mapping_19-10-2018.tsv
mouse_id_mapping_19-10-2018     Mus musculus (19-10-2018)       mouse_id_mapping        /home/dchristiany/proteore_project/galaxy/tool-data/id_mapping/mouse_id_mapping_19-10-2018.tsv
```

It is not obvious here but the data table is separated by tabulation (not spaces).
It seems that only the value columns can be selected to filter, even when I put the column name in the key prarameter. 

I also got the following error : 
`return [(disp_name, optval, selected) for disp_name, optval, selected in options if not compare_value(optval, value)]`
`ValueError: too many values to unpack`

Maybe it is a common mistake but I didn't find a solution.

**Comment by davidchristiany** [comment]
I found this topic : 

https://github.com/galaxyproject/galaxy/issues/2987

This issue is supposed to be fixed right ? 
This error is due to filter_options which returns an inexpected list.

**Comment by peterjc** [comment]
I suspect that what I reported as https://github.com/galaxyproject/galaxy/issues/2987 wasn't entirely fixed by https://github.com/galaxyproject/galaxy/pull/6103 by @nsoranzo, but I never did get back to the original motivating use case.

**Comment by nsoranzo** [comment]
@peterjc No, this is a completely different issue.

@davidchristiany Unfortunately the `remove_value` filter was not developed with your case in mind. As far as I know, the only tool that employs it is [maf_to_interval](https://github.com/galaxyproject/galaxy/blob/dev/tools/maf/maf_to_interval.xml), where it is used to filter dataset metadata.

I've created pull request https://github.com/galaxyproject/galaxy/pull/6914 to extend the `remove_value` filter to general data tables. When merged

```xml
<filter type="remove_value" value="rat_id_mapping_19-10-2018"/>
```
should do what you want (note that the `key` attribute is not necessary).

P.S.: this issue is not about a tools-iuc tools, so should have been reported to https://github.com/galaxyproject/galaxy/issues

**Comment by davidchristiany** [comment]
Thanks a lot ! I will wait for the pulll request to be validate.

PS : I will be more careful next time when I create an issue.
