### ISSUE TITLE
How to use tool shed?

### ISSUE THREAD

**Issue by simson7856** [galaxyproject/tools-iuc#2220]
Dear whom it may concern,

I am now learning to analyze ChIP seq data on Galaxy platform. I have also tried on MAnorm and DEscan2 for normalization and comparison between samples. During my research, I found that MAnorm got its tool shed in Galaxy. May I know how to install the MAnorm program into Galaxy platform and use it online?
Please advise and thanks for your help.

Best Regards,
Simson

**Comment by bgruening** [comment]
Hi @simson7856,

you can install tools by following this explanation: https://galaxyproject.org/admin/tools/add-tool-from-toolshed-tutorial/ but you need to be admin. Otherwise, you need to convince the Admin of your instance to install this tool.

A better way to ask those questions is to open a ticket in our help forum here: https://help.galaxyproject.org/

Ciao and happy new year,
Bjoern

**Comment by simson7856** [comment]
Dear Bjoern,

Thanks for your reply. May I know how to find the admin? It is because I create my account privately and don't know who to contact with.
Please advise and thanks for your help.

Best Regards and happy new year,
Simson
