### ISSUE TITLE
Tool error with Bowtie2 2.3.4.2

### ISSUE THREAD

**Issue by mpaya** [galaxyproject/tools-iuc#2438]
Hi. I used Bowtie2 2.3.4.2 for data analysis and now I'm preparing a galaxy instance to share the exact methods I used on my analysis to comply with publishing reproducible research. But while testing my workflows, the newly installed Bowtie2 '17062a0decb7' is not working, while the one installed on my old galaxy works just fine. The only errors are:
* `tool error`
* `Unable to finish job`

I used the docker galaxy quay.io/bgruening/galaxy:18.05 both times. May it be an issue with samtools? Can it be fixed?
Thank you!

**Comment by mvdbeek** [comment]
Hi @mpaya, great that you are through in publishing your research in a reproducible way!

This is most likely a problem with the docker image. Make sure that the dependencies for the `Set External Metadata` tools are installed in the admin panel (Admin -> Manage tool dependencies -> select the row that contains "Set External Metadata" and click `install dependencies via Conda`).

I believe that has been fixed in newer versions of the docker image, but if this is still an issue please report this at https://github.com/bgruening/docker-galaxy-stable/issues

**Comment by mpaya** [comment]
Thanks for your prompt response @mvdbeek. On the Admin panel I cannot find that option, the currently available are:
```
## Tool Management
Install new tools
Manage tools
Manage metadata
Manage whitelist
Manage dependencies
View lineage
View migration stages
View error logs
```
And installing the latest docker version gives just the same problem, though I'll ask there as suggested. On Manage dependencies, the ones for bowtie2 appear to be installed. No clue on the error logs.
Miriam

**Comment by nsoranzo** [comment]
`Manage dependencies` is the right menu, but check the line for the `Set External Metadata` tool.

**Comment by mpaya** [comment]
That option is not here, only change views and install/uninstall checked dependencies. Anyways I just realized that the tool works and the output is visible, but the status is fail and breaks the workflow. I'll ask on the docker [issue](https://github.com/bgruening/docker-galaxy-stable/issues/489)

Thanks for your support :)

**Comment by nsoranzo** [comment]
`Set External Metadata` is not an option, it's a tool (as `Bowtie2`), look for it in the first column (`Used by`).

**Comment by mpaya** [comment]
Ok found it, but tools are not clickable so I didn't expect it there.
