### ISSUE TITLE
Q: multiple channels in idr-download 

### ISSUE THREAD

**Issue by sunyi000** [galaxyproject/tools-iuc#2936]
Hi,

just asking if it's possible for this tool here 

https://github.com/galaxyproject/tools-iuc/tree/master/tools/idr_download

to allow multiple channel inputs?

for example, If upload an imageids file contains images across multiple channels, can we specify a comma separated channel list as input to the $channel parameter?

Thanks very much

**Comment by beatrizserrano** [comment]
As far as I know, the IDR API provides the function [getTile](https://github.com/galaxyproject/tools-iuc/blob/master/tools/idr_download/idr_download_by_ids.py#L85), for just one plane. I can't think of a use case why one would want to get multiple channels and save just one image; for me, either one takes the whole image or just the channel that is going to be analysed.

**Comment by sunyi000** [comment]
for example, for secretion plate/screen (sorry I'm not sure about the name)
the input will be one imageID file contains 1 id per line.. some of them from 'dapi' channel, some of them from 'nucleus-dapi' channel..what would be the best way to download everything in one run?
currently I guess I will need to run twice with the same imageid file but different 'channel' name?

thx

**Comment by beatrizserrano** [comment]
Ah, I see. That's an issue with the metadata associated with the images: the same channel is labelled differently (`dapi`, `nucleus-dapi`) for some images within the same dataset. I'm not sure whether that issue should be fixed by the tool... in part because we know about this case, but there might be [many others](https://github.com/idr-contrib/community/issues/22). I think that the metadata issues should have been addressed upstream. But again, there are probably other cases that are out of our hands. In the worst-case scenario, the user that is aware of the problem can run the tool twice with the two different labels.

**Comment by bgruening** [comment]
> In the worst-case scenario, the user that is aware of the problem can run the tool twice with the two different labels.

I don't see anything wrong here. In a second step you could also merge then both collections into one. Those issues should also reported upstream?

**Comment by sunyi000** [comment]
closed
