### ISSUE TITLE
Include cairo in package_r_* or not? 

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/tools-iuc#304]
Currently package_r_3_2_1 depends on package_cairo_1_12_14, because cairo-support is explicitly compiled into R (./configure --with-cairo). This specific version of cairo does not compile on gcc-4.9 (see Issue #294 ). Cairo can however be dynamically loaded into a R version that was compiled without cairo support. 
Should we therefore abandon compiling in cairo into R? This should give us more flexibility of which cairo version we would like to install into R.
A quick search among tools-iuc tools suggests that currently this would affect only vegan, which should be changed to explicitly depend on cairo.
The alternative is to switch R_3_2_1 (and older versions) to depend on cairo-1.14.2.
What do you think, @yhoogstrate @bgruening ?

**Comment by bgruening** [comment]
As far as I remember we need R depend on cairo for some drawing capabilities.
My preferred solution would be to release a R_3_2_2 version with the new updated cairo dependency and update the wrapper.

**Comment by mvdbeek** [comment]
I tested this on docker-galaxy-stable with package_r_3_2_1_without_cairo (testtoolshed):
```
http://gforge.se/2013/02/exporting-nice-plots-in-r/
```
Do you have any idea which tools would require baked-in cairo? Perhaps we change the already released R version to use cairo-1.14.2, and to release newer version of R without cairo? This way we don't break anything for people that depend on R right now, and if tool developers change the R version they will notice in testing that Cairo is not included anymore?

**Comment by yhoogstrate** [comment]
I did not test this because by that time cairo didn't work either, but I guess cairo is neccesairy to solve:
https://biostar.usegalaxy.org/p/9170/  So I would prefer cairo as part of R.

At the link http://sourceforge.net/p/mingw-w64/bugs/396/ they claim to solve 1.12.14 with a diff file:
```
--- mingw64-x-cairo-1.12.14.orig/build/configure.ac.warnings
+++ mingw64-x-cairo-1.12.14/build/configure.ac.warnings
@@ -39,7 +39,7 @@ dnl options. Namely, the following:
dnl -flto working really needs a test link, not just a compile
safe_MAYBE_WARN="$MAYBE_WARN"
-MAYBE_WARN="$MAYBE_WARN -flto"
+MAYBE_WARN="$MAYBE_WARN -flto -ffat-lto-objects -fuse-linker-plugin"
AC_TRY_LINK([],
int main(int argc, char **argv) { return 0; }
,[],[
--- mingw64-x-cairo-1.12.14.orig/configure
+++ mingw64-x-cairo-1.12.14/configure
@@ -18162,7 +18162,7 @@ MAYBE_WARN="$MAYBE_WARN -erroff=E_ENUM_T
safe_MAYBE_WARN="$MAYBE_WARN"
-MAYBE_WARN="$MAYBE_WARN -flto"
+MAYBE_WARN="$MAYBE_WARN -flto -ffat-lto-objects -fuse-linker-plugin"
cat confdefs.h - <<_ACEOF >conftest.$ac_ext
/ end confdefs.h. /
```
Because you can't include a patch file within a package definition (allows only 1 file), you could hack the tool_dependencies such that it creates the diff and patches the package, but this is kind of upgrading the package locally. But if you solve it this way, package_cairo_1_12_14 doesn't need to be deprecated.

> Perhaps we change the already released R version to use cairo-1.14.2, and to release newer version of R without cairo?

I would go for solving R 3.2.1 as well, since we don't know how many non iuc/dev-team tools depend on it. If we solve it within R 3.2.1, only a re-up to the TS is neccessairy.

**Comment by mvdbeek** [comment]
@yhoogstrate OK, I can definitely patch with sed, and that's a good solution.

Though I think we really don't need cairo (in new R releases), and including it is causing more trouble than necessary.
The post you linked is not very likely linked to cairo, but to X11 support being compiled inot R, when X11 is actually not available.

**Comment by yhoogstrate** [comment]
Oh yeah I didn't mention everything. R doesn't support and compile with X11 which is logical, because it should work on machines that have no X installed too. If I remember correctly, the problem didn't occur on Desktop machines, but only on machines without X11. When I tried to solve it, I thought the anwers was by using cairo libraries to do the drawing rather than X11, but I never got that far so I should not make the decision.

I was thinking of the following solution because it recreates the diff file and is line number based  (didn't actually test it...):
```
touch configure_patch.diff

echo '--- mingw64-x-cairo-1.12.14.orig/build/configure.ac.warnings' >> configure_patch.diff
echo '+++ mingw64-x-cairo-1.12.14/build/configure.ac.warnings' >> configure_patch.diff
echo '@@ -39,7 +39,7 @@ dnl options. Namely, the following:' >> configure_patch.diff
echo 'dnl -flto working really needs a test link, not just a compile' >> configure_patch.diff
echo 'safe_MAYBE_WARN="$MAYBE_WARN"\' >> configure_patch.diff
echo '-MAYBE_WARN="$MAYBE_WARN -flto"' >> configure_patch.diff
echo '+MAYBE_WARN="$MAYBE_WARN -flto -ffat-lto-objects -fuse-linker-plugin"' >> configure_patch.diff
echo 'AC_TRY_LINK([],' >> configure_patch.diff
echo 'int main(int argc, char **argv) { return 0; }' >> configure_patch.diff
echo ',[],[' >> configure_patch.diff
echo '--- mingw64-x-cairo-1.12.14.orig/configure' >> configure_patch.diff
echo '+++ mingw64-x-cairo-1.12.14/configure' >> configure_patch.diff
echo '@@ -18162,7 +18162,7 @@ MAYBE_WARN="$MAYBE_WARN -erroff=E_ENUM_T' >> configure_patch.diff
echo 'safe_MAYBE_WARN="$MAYBE_WARN"' >> configure_patch.diff
echo '-MAYBE_WARN="$MAYBE_WARN -flto"' >> configure_patch.diff
echo '+MAYBE_WARN="$MAYBE_WARN -flto -ffat-lto-objects -fuse-linker-plugin"' >> configure_patch.diff
echo 'cat confdefs.h - <<_ACEOF >conftest.$ac_ext' >> configure_patch.diff
echo '/ end confdefs.h. /' >> configure_patch.diff

patch configure_patch.diff
```

But whatever is more comfortable to you!

**Comment by mvdbeek** [comment]
I'm testing now with
```bash
sed -i.bak 's|MAYBE_WARN="$MAYBE_WARN -flto"|MAYBE_WARN="$MAYBE_WARN -flto -ffat-lto-objects -fuse-linker-plugin" |' configure build/configure.ac.warnings
```
it definitely compiled on gcc-4.9, i'll check some older compilers now.

**Comment by bgruening** [comment]
Unfortunately not but maybe @davebx. I also remember someone from the mailing list needed cairo in R. Can you check if RCairo compiles id Cairo is not part of R?
I can live with both solutions. What ever the easiest for you.

**Comment by mvdbeek** [comment]
> Can you check if RCairo compiles id Cairo is not part of R?

Not sure I get what you mean ;)

Definitely least amount of work is to fix cairo_1_12_14 with the sed line I posted above, I will open a PR if testing succeeds.
But I think in the long run we can save ourselves some trouble by not including cairo, with tool authors being responsible to define whatever cairo version they need. 
I saw some posts by @christian-b having trouble with cairo, I am imagining the troubleshooting being much easier if you can just "flip-out" the cairo version independently of the base R version.

**Comment by bgruening** [comment]
>> Can you check if RCairo compiles id Cairo is not part of R?

>Not sure I get what you mean ;)

Sorry, I mean: Can you install the R package RCairo if R is not compiled against Cairo?

**Comment by mvdbeek** [comment]
@bgruening you mean this one https://cran.r-project.org/web/packages/Cairo/index.html? Yes, I tested this, works fine.

**Comment by bgruening** [comment]
Than I'm fine with removing it. @davebx should have a last call as I think he introduced it.
I think if we can get DESeq2 and DEXSeq compiled we can be confident that this works well for other packages as well.
Thanks @mvdbeek

**Comment by Christian-B** [comment]
I have had a lot of trouble with Cairo in R

Thinks I discovered included.

https://testtoolshed.g2.bx.psu.edu/view/iuc/package_r_3_2_1/fefdc0b8349a
-tries to use: https://depot.galaxyproject.org/package/linux/x86_64/R/R-3.2.1-Linux-x86_64.tar.gz
    This has hard coded paths in the env.sh file so could not be used.
-These should be prepend to rather than "set to"
<environment_variable action="set_to" name="PKG_CONFIG_DIR">$INSTALL_DIR/lib/pkgconfig:$INSTALL_DIR/share/pkgconfig</environment_variable>
<environment_variable action="set_to" name="PKG_CONFIG_PATH">$INSTALL_DIR/lib/pkgconfig:$INSTALL_DIR/share/pkgconfig</environment_variable>

You also need:
package_libxml2_2_9_1
and
package_fontconfig_2_11_1

to install cairo into R

Christian

PS. I did get it working once but then messed around and have not got it working again.
I am getting weird dependencies but am not sure if that is an error on my part of galaxies at this point.


________________________________

**Comment by mvdbeek** [comment]
@christian-b yeah, galaxy's dependency resolving is a bit broken right now if you mess with dependencies of previously uninstalled packages (See https://github.com/galaxyproject/galaxy/issues/667). 
If you want to be sure of your tool/package, start up a clean instance and experiment in there. Sorry that there is no way around it yet. I can give you hand once we get this stuff here fixed.

**Comment by mvdbeek** [comment]
@bgruening I might have been fooled by the pre-compiled R binary. I'll have to do some more testing to see if we can really live without baked-in cairo support.

**Comment by nsoranzo** [comment]
@mvdbeek Is this fixed by your recent work?

**Comment by mvdbeek** [comment]
Yes, it should be, we continue to build R with cairo.
