### ISSUE TITLE
Include goseq tool

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/tools-iuc#327]
Is there interest to include goseq (http://dx.doi.org/doi:10.1186/gb-2010-11-2-r14 http://www.bioconductor.org/packages/release/bioc/html/goseq.html) into tools-iuc?
Is anybody already working on this? @bgruening @yhoogstrate ?
One difficulty is the need tor gene length, but we could take this from gtf/gff/bed files ...

**Comment by bgruening** [comment]
@mvdbeek GO annotation is really important for post-processing and David is not sufficient anymore. So from me a strong yes, please.
But we should try hard to not rely on web services. As you pointed out the gene-lenght is taken from USCS:

```
goseq relies on the UCSC genome browser to provide the length information for each gene.
```

If we can work around this limitation this would be a wonderful addition.
Also see https://github.com/galaxyproject/tools-iuc/pull/6 for GO related issues.

**Comment by mvdbeek** [comment]
I think gene length would be straightforward to get, since we already have the information when we produce gene-count tables (@yhoogstrate's featureCounts wrapper even outputs the length information).
I'm more worried about the actual GO data ...

**Comment by yhoogstrate** [comment]
I am not working on it but it looks like a cool package, although it might be complicated to wrap.

"To do this, it retrieves the data from the database of gene lengths maintained in the package *geneLenDataBase*. This is performed by the getlength function in the following way:"
```
> len=getlength(names(genes),"hg19","ensGene")
> length(len)
[1] 22743
> length(genes)
[1] 22743
> head(len)
[1] 247 3133 1978 466 1510 954
```
That's from the GOSeq manual. It should only convert a list of gene names into a list of corresponding lengths. If you have something that can download all ENSEMBL genes lengths, you can solve this issue by creating a geneLenDataBase datamanager rather easily I suppose?

**Comment by mvdbeek** [comment]
@yhoogstrate yes, but you can also feed in a vector of gene lengths ... given that a GFF/GTF/BED file was used in the DE calling seems more straightforward, at least for an initial package.
I was rather thinking to write a data manager for getting the GO data associated to the genome's dbkey.

**Comment by yhoogstrate** [comment]
I know, but there could be pitfalls. When I see the lengths in the manual, they probably do not represent genomic sizes of genes (247 to 3133 is quite small), but transcriptomic. If you stay stick to what they provide you can rule out any mistake introduced by your own implementation, because this requires scripting to get these lengths correctly. Similarly, if you need these lengths for something else, why would you not have them made available via a datamanager.
It's not that I'm voting against what you propose, but I just like to see the possibilities before we take any action ;). It would also be possible to provide the lengths "from history" if there is no data-manager version available.

Another piece from the manual: "However, because the process of fetching the length of every
transcript is slow and bandwidth intensive, goseq relies on an offline copy of this information
stored in the data package geneLenDataBase."
The geneLenDataBase seems to be some kind of local cache of these lengths.

**Comment by mvdbeek** [comment]
@yhoogstrate absolutely, I appreciate the discussion! But what featureCounts is outputting is not the genomic length, but the total sum of the length of the exons (If your feature is exons), so this would be the correct length. (Have to verify though). But say, you want to profile UTRs, or full gene length, or introns (weird, but the task can come up!), then you would get the wrong length using a datamanager
And those length are exactly and 100% what was used to get to the count table, so this is the best possible option, for me. Also users like to sometimes use their own GTF/GFF, or the GFF they got from a transcript assembler. I' will check the lengths that featureCounts produces!

**Comment by mvdbeek** [comment]
So featureCounts seems to be outputting the correct length:
```
Geneid	101: S3.hisat2_aligned	Length	Geneid	101: S3.hisat2_aligned	Length
FBgn0086917	0	1767	FBgn0086917	0	105
FBgn0010247	409	3112	FBgn0010247	9	127
FBgn0086378	3266	1290	FBgn0086378	319	753
```

First 3 columns are exons, last 3 are UTRs.

**Comment by bgruening** [comment]
What do we need to do here to get GOseq into IUC?

**Comment by mvdbeek** [comment]
Goseq itself should be ready, I got a bit stuck on extracting category information from the different genome packages, but that would be a different tool anyway. I'll make a WIP PR.

**Comment by bgruening** [comment]
:+1:  thanks!

**Comment by yhoogstrate** [comment]
@mvdbeek has resolved this issue in https://github.com/galaxyproject/tools-iuc/pull/1034 :+1:
