### ISSUE TITLE
DESeq2 issue with multi-factor design

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/tools-iuc#332]
This is using 2.1.8.2 from the testtoolshed.
I got the following input parameters:
```

Input Parameter	Value	Note for rerun
Specify a factor name	Infection	
Specify a factor level	Virus	
Counts file(s)	185: S1.counts, 189: S3.counts, 193: S5.counts	
Specify a factor level	Control	
Counts file(s)	187: s2.counts, 191: S4.counts, 195: S6.counts	
Specify a factor name	Time_of_prep	
Specify a factor level	1st	
Counts file(s)	185: S1.counts, 187: s2.counts	
Specify a factor level	2nd	
Counts file(s)	189: S3.counts, 191: S4.counts, 193: S5.counts, 195: S6.counts	
Visualising the analysis results	True	
Output all levels vs all levels of primary factor (use when you have >2 levels for primary factor)	False	
Fit type	parametric	
Turn off outliers replacement (only affects with >6 replicates)	False	
Turn off outliers filtering (only affects with >2 replicates)	False	
Turn off independent filtering	False
```
In words, 6 samples, of which 3 are infected, 2 were taken on timepoint 1 and 4 on timepoint 2,
so I would have 2 factor with each 2 factor levels.

This crashes with the following message:
```
Tool execution generated the following error message:
Fatal error: An undefined error occured, please check your intput carefully and contact your administrator.
Creating a generic function for 'nchar' from package 'base' in package 'S4Vectors'
Error in scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  : 
  line 2 did not have 3 elements
Calls: DESeqDataSetFromHTSeqCount -> lapply -> lapply -> FUN -> read.table -> scan
The tool produced the following additional output:
DESeq2 run information

sample table:
                   Infection Time_of_prep
dataset_138391.dat     Virus          1st
dataset_138395.dat     Virus          2nd
dataset_138399.dat     Virus          2nd
dataset_138393.dat   Control          1st
dataset_138397.dat   Control          2nd
dataset_138401.dat   Control          2nd

design formula:
~Time_of_prep + Infection


primary factor: Infection 
other factors in design: Infection 

---------------------

``` 

I am guessing `other factors in design: should be` `Time_of_prep`, not `Infection`.
Any idea, @yhoogstrate , @bgruening ?

**Comment by mvdbeek** [comment]
It's not actually related to multifactor design (even if the error is a bit misleading),
I was producing output with header lines ... I'll see what can be done to make the error more obvious.

**Comment by yhoogstrate** [comment]
I would like to see that too. Afaik DESeq2 is now only compatible with HTSeq counts (and not with featureCounts).

**Comment by bgruening** [comment]
@yhoogstrate do you know offhand if featureCounts produces output which are recognised as `has_comment` by Galaxy? Then we could simply add a metadata check into the DESeq2 (DEXSeq?) wrapper?

**Comment by mvdbeek** [comment]
@bgruening `has_comment` would mean that in the history it would say something like "has 1 comment"?  No, it doesn't say this. I guess it's relatively safe to assume that a first line that starts with gene.* or Gene.* and non-integer text in the remaining column(s) would stem from feautureCounts or other tools that produce count tables.

**Comment by yhoogstrate** [comment]
If I remember correctly, the extensive output contains comment lines that start with a hashtag.

I think comment lines and a header line are two different properties of a table, and using such hacks may introduce problems at the long term. Imagine that the definition of tabular files once gets an extra metadata feature for header-lines, then for backwards compatibility you always have to check comment lines too. So I would only go for a metadata check if the metadata explicitly describes that it contains a header line.

What @mvdbeek proposes seems more logical to me. I know R can be nasty with automatically checking this because the number of columns in the headerline must be 1 smaller than the other lines, so the most logical way to me should be to manually check if the 2nd element of the 1st row is numerical. If we do this we should make sure that all these genes are kicked out:
```
exclude_HTSeq <- c("no_feature","ambiguous","too_low_aQual","not_aligned","alignment_not_unique")
exclude_DEXSeq <- c("_ambiguous","_empty","_lowaqual","_notaligned")
```
Those of HTSeq I once checked, so they should be fine.

**Comment by bgruening** [comment]
@mvdbeek I'm not sure this is to dangerous.
But Galaxy has a really advanced metadata system we never really use. So if anyone of you wants to play with it. Here is my suggestions.
We had to featureCounts something similar to this and try to get `header` set to an appropriate value:

https://github.com/bgruening/galaxytools/blob/master/tools/text_processing/text_processing/cut.xml#L110

Then we ask in DE(X)Seq if there is an header, if so we ignore it.

@yhoogstrate just saw your comment now. We can set the metadata to some degree in featureCounts so this should be the cleanest way, without guessing.

**Comment by mvdbeek** [comment]
@bgruening yes, that sounds good. I'm not yet familiar with this.

**Comment by mvdbeek** [comment]
Should I close this in favour of a new issue or PR, or we leave it open until we do something about it?

**Comment by bgruening** [comment]
@mvdbeek me too. But we should make more use of this and probably document it properly.
Leave it open. Maybe someone wants to play with the metadata system.

**Comment by yhoogstrate** [comment]
>  and probably document it properly

I think this is the biggest issue for metadata, and this is why it prevents (at least me) from using it. I want to take a look into it and see if I can get it working at the featureCounts side.

**Comment by yhoogstrate** [comment]
I figured out how to do this.

To change a metadata value (e.g. named 'has_header_line') in a history item, the metadata name must be reserved and defined in the datatype. E.g. for tabular files only the following metadata elements are available and can be changed via a tool xml:

```
MetadataElement( name="comment_lines", default=0, desc="Number of comment lines", readonly=False, optional=True, no_value=0 )
MetadataElement( name="data_lines", default=0, desc="Number of data lines", readonly=True, visible=False, optional=True, no_value=0 )
MetadataElement( name="columns", default=0, desc="Number of columns", readonly=True, visible=False, no_value=0 )
MetadataElement( name="column_types", default=[], desc="Column types", param=metadata.ColumnTypesParameter, readonly=True, visible=False, no_value=[] )
MetadataElement( name="column_names", default=[], desc="Column names", readonly=True, visible=False, optional=True, no_value=[] )
MetadataElement( name="delimiter", default='\t', desc="Data delimiter", readonly=True, visible=False, optional=True, no_value=[] )
```

https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/datatypes/tabular.py#L34

Because from these metadata variables you can not deduce whether there is a header line, you would need to add a new definition for that, probably something like:

```
MetadataElement( name="has_header_line", default=False, desc="Is the first data line a column header?", readonly=False, visible=True, optional=True, no_value=False )
```

Or maybe it's handier to create it as 'header_line', which represent the exact line where the header can be expected (but this should be equal to metadata.comment_lines + 1). Doing so it could solve an issue I never actually reported. For input params of the type data_column the comment lines are not being skipped:

```
#header1
#header2
#header3
c1	c2	c3
a	2	4
b	1	4
c	4	3
```
```
<param type="data_column" data_ref="tabular_file" numerical="True" multiple="true" use_header_names="true" />
```
Picks the first line to determine the columns on, also when the input file has the comments are enabled.:
![screenshot from 2015-10-16 13 57 50](https://cloud.githubusercontent.com/assets/2264697/10541076/699519ba-740e-11e5-8578-36899a1c6725.png)

By picking the 'metadata.header_line' this could be solved, although comment_lines+1 would be fine too.

-----
To set the metadata you could:
- Set it in the tool xml that generates the file
- Let the Tabular.py parse this but this is not flawless.

At the tool xml part we should do it this way:
```
<data format="tabular" name="output" label="${tool.name} on ...">
	<actions>
		<action name="has_header_line" type="metadata" default="1" />
	</actions>
</data>
```

Would you like to see this change to Tabular.py or would you prefer another solution?

**Comment by bgruening** [comment]
@yhoogstrate awesome! Sorry, on my way to a meeting, so just a quick note. Happy to chat with you about this later.
I think we can build this without modifying the tabular.py file. We simply remove the header from featureCounts, but we attach the column names as `column_names`. This would enable us to use the column_picker to deliver the column names as select item.
In general I'm not a fan of providing column names inside of the file. These are metadata and it should be treated as metadata, imho!

**Comment by yhoogstrate** [comment]
Hi Bjoern,

I know we had this discussion once before. My major objection is that by removing the header column we are modifing files in a way that they become different than the original output, only to make it 'fit' within galaxy. The major cause of this is of course that there is (or I am not aware of) no unified standard to present this type of data, in contrast to e.g. alignments (BAM,CRAM) or mutations (VCF). Modifying the featureCounts tabular files would not be an issue if galaxy was a completely encapsulated system (in terms of in- and output of files). But I think that where files go in and out galaxy this introduces problems. If a user runs featureCounts outside of galaxy (yes, these people exist!), uploads the data into galaxy and want to analyse the results in DESeq, they must modify the file (remove the header) for compatibility. This is user unfriendly and we should have the knowledge to overcome this. Similarly, when columns are being removed by the galaxy wrapper and a user downloads the file, it has no columns. I can imagine it is frustrating to download files and modifying them by hand again.

> In general I'm not a fan of providing column names inside of the file. These are metadata and it should be treated as metadata, imho!

You are right that it is just metadata, but if you reason that way we should strip bam and sam headers too. But here we neglect that the principal of galaxy is that it is a file based and organizing system and therefore you don't want files to be any different than if you would run the same tool outside of galaxy. The metadata can still be interpreted in the back-end and I would be fan of this too, but I don't see this as a reason to strip it from the files. I know header colums are just a small thing but I think it comes with larger implications and I see this as fitting featureCounts into galaxy instead of fitting galaxy around featureCounts. I would rather change Tabular.py or create/find and convert to a uniform file format than to post-modify the featureCounts output.

Sorry for the resistace..

**Comment by mvdbeek** [comment]
I wholeheartedly agree with @yhoogstrate reasoning. Best would be to have a header that is marked as comment, together with metadata that is equivalent to the header line. Is this possible?

I know this would be larger change in the galaxy codebase, but would it be possible to have "tool-specific datatypes"? So for example featureCounts and htseq would produce tabular output of class CountTable, which would be a subclass of tabular, which would be defined within the tools datatypes.conf? Or maybe that is already possible and I'm re-inventing the wheel?

**Comment by bgruening** [comment]
> I know we had this discussion once before. My major objection is that by removing the header column we are modifing files in a way that they become different than the original output, only to make it 'fit' within galaxy. 

I see it more like we fitting them to other tools, not Galaxy. We all do the same in R and Python if we import data in dataframes, isn't it?
There are so many tools, especially if you are combining tools from different areas of bioinformatics (genomics, proteomics ...), that can not deal with some strange file formats.
For example blockbuster produces a BED-file-like output with random lines inserted starting with '>'. So a mixture of FASTA and BED. I think we should change those file to fit to other tools (not because of Galaxy) to be consumed. The same you would do inside a script in which you define your pipeline, I guess. Moreover, tabular is tab separated and most of our tools work on these data. I try usually to convert comma-separated files to tabular inside the wrapper. Simply because it is user-friendly and saves the user one extra step and us as admins on extra file in our storage. And there are many other examples where we need to define a standard in Galaxy. See the BAM files discussion. In our context BAM is coordinate sorted. We need to have a special datatype for name-sorted BAM. But one sane default is needed, imho.
And tabular is imho defined tab separated file without metadata. Otherwise we need to define these as comment lines. 

> The major cause of this is of course that there is (or I am not aware of) no unified standard to present this type of data, in contrast to e.g. alignments (BAM,CRAM) or mutations (VCF). Modifying the featureCounts tabular files would not be an issue if galaxy was a completely encapsulated system (in terms of in- and output of files).

This is a matter of usability, I tend to write tools as usable inside Galaxy as possible. Everyone who can download dataset and process it with R, Python whatever can add meta data to it. Especially, if you use bioblend and can attach the meta-data columns back to the file if you like to.
We can always define a new file type, which can have additional features.

> But I think that where files go in and out galaxy this introduces problems. If a user runs featureCounts outside of galaxy (yes, these people exist!), uploads the data into galaxy and want to analyse the results in DESeq, they must modify the file (remove the header) for compatibility. 

Why? The tool should be smart enough to handle this.
If you define your own file type you need to manually specify it during upload. I don't think this is more user-friendly.

>This is user unfriendly and we should have the knowledge to overcome this. 

For power users yes, not for the others. (Note: I'm talking here about the general issue that we need to define sane defaults. This featureCounts example is a very simple case.)

>Similarly, when columns are being removed by the galaxy wrapper and a user downloads the file, it has no columns. I can imagine it is frustrating to download files and modifying them by hand again.

I guess, power user can handle this. Or we can attach meta-data back to the file.
In the end it's a trade-off between different user groups and tool development is always such a trade-off. Do we export the Xms memory flag to the user or --verbose? Which parameters do we hide under 'advanced options'. Do we include all parameters at all? ...

>> In general I'm not a fan of providing column names inside of the file. These are metadata and it should be treated as metadata, imho!

> You are right that it is just metadata, but if you reason that way we should strip bam and sam headers too. 

Why? This has no implication to the usability of other tools, isn't it?
Again, featureCounts is a bad example but consider worse examples like the FASTA-BED file mentioned above.

> But here we neglect that the principal of galaxy is that it is a file based and organizing system and therefore you don't want files to be any different than if you would run the same tool outside of galaxy. 

I disagree. We sort BAM files by default to make it more usable. I break one-line FASTA files into 80 chars ones, just because it's more pleasant to view etc ...

> The metadata can still be interpreted in the back-end and I would be fan of this too, but I don't see this as a reason to strip it from the files. I know header colums are just a small thing but I think it comes with larger implications and I see this as fitting featureCounts into galaxy instead of fitting galaxy around featureCounts. 

As I said, I'm fine with featureCounds this is a very simple example but there are many bad formats out there and imho we need to protect our users from this. There is a reason everyone is writing a wrapper for the wrapper of some tool (and here I'm talking not about Galaxy) :)

> I would rather change Tabular.py or create/find and convert to a uniform file format than to post-modify the featureCounts output.

Tabular does not have headers as far as I know. It can have comment lines.
If you want to do this you can define your own file format.

> Sorry for the resistace..

Nothing to be sorry for, I appreciate the discussion.
For me developing wrappers is more than writing or generating XML files. Here we have to unique opportunity to create outputs that fits in well to other tools. We can make the hand-shake happen even across interdisciplinary research. 


> I wholeheartedly agree with @yhoogstrate reasoning. Best would be to have a header that is marked as comment, together with metadata that is equivalent to the header line. Is this possible?

Yes, I think so.
Still, imagine a file with 5 headers, the 5th is the column description and now you want to sort this file. Unfortunately, these files exist :(

> I know this would be larger change in the galaxy codebase, but would it be possible to have "tool-specific datatypes"? So for example featureCounts and htseq would produce tabular output of class CountTable, which would be a subclass of tabular, which would be defined within the tools datatypes.conf? Or maybe that is already possible and I'm re-inventing the wheel? 

Oh, yes this in discussed a lot. We can define a data type for count-data, but we can not even make this unique for htseq-count, featureCounts and DEXSeq-counts ;)
I'm not sure we really want to have this complexity in Galaxy. We are working now on literature mining software, imaging, astronomy ... so many different tabular files.

**Comment by peterjc** [comment]
Similar issues with many of the tabular files in https://github.com/peterjc/pico_galaxy/tree/master/tools (some I have to massage the output anyway to make it tabular) and https://github.com/peterjc/galaxy_blast (e.g. the pick-you-own column tabular output). Allowing the tool wrapper to set column names in the Galaxy metadata for the generic ``tabular`` datatype seems the best way forward.

**Comment by mvdbeek** [comment]
> >I wholeheartedly agree with @yhoogstrate reasoning. Best would be to have a header that is marked as comment, together with metadata that is equivalent to the header line. Is this possible?

> Yes, I think so.
> Still, imagine a file with 5 headers, the 5th is the column description and now you want to sort this file. Unfortunately, these files exist :(

I didn't consider that case. Ideally galaxy would ignore things it recognised as headers (or comments),
if the tool didn't specifically ask for the metadata information. But I can see how this gets complex very quickly.

>> I know this would be larger change in the galaxy codebase, but would it be possible to have "tool-specific datatypes"? So for example featureCounts and htseq would produce tabular output of class CountTable, which would be a subclass of tabular, which would be defined within the tools datatypes.conf? Or maybe that is already possible and I'm re-inventing the wheel?

> Oh, yes this in discussed a lot. We can define a data type for count-data, but we can not even make this unique for htseq-count, featureCounts and DEXSeq-counts ;)

Why not? It's true we'd need to do this for htseq-count, featureCounts and DEXSeq-counts, but if we decide on a common datatype with common metadata, then we'd only need to map Identifiers and counts in the datatype. I'm a bit vague here, admittedly, but it would be nice if galaxy tools could transparently handle the native dataformats produced by htseq-count, featureCounts and DEXSeq-counts, since the kind of information they provide is the same.

**Comment by bgruening** [comment]
>> Oh, yes this in discussed a lot. We can define a data type for count-data, but we can not even make this unique for htseq-count, featureCounts and DEXSeq-counts ;)

>Why not? It's true we'd need to do this for htseq-count, featureCounts and DEXSeq-counts, but if we decide on a common datatype with common metadata, then we'd only need to map Identifiers and counts in the datatype. I'm a bit vague here, admittedly, but it would be nice if galaxy tools could transparently handle the native dataformats produced by htseq-count, featureCounts and DEXSeq-counts, since the kind of information they provide is the same.

Different number of columns, different headers/comment lines. Thinking about it I don't know what is similar between them ;)
featureCount is even worse, as it does not mark the comment line with `#` or similar symbols. 
So we need to recognise `Geneid 1:`, which is not really unique. Also please consider what happens if this identifier is changing between featureCounts versions, for example to `Gene-ID 1:`. You need to have a new data type to detect this. Versioned datatypes are currently not supported.

**Comment by mvdbeek** [comment]
> Different number of columns, different headers/comment lines. Thinking about it I don't know what is similar between them ;)
Isn't that what metadata is good for?
> featureCount is even worse, as it does not mark the comment line with # or similar symbols. 
> So we need to recognise Geneid 1:, which is not really unique. Also please consider what happens if this identifier is changing between featureCounts versions, for example to Gene-ID 1:. You need to have a new data type to detect this. Versioned datatypes are currently not supported.

Well, if this happens, the featureCounts wrapper should introduce a new datatype. I'm seeing this from the angle of the tool wrapper "explaining" what kind of data it is producing. If tools can register new datatypes, I don't see the harm of having a few hundred different datatypes.

**Comment by mvdbeek** [comment]
Well it's a complex issue, and I am not even sure what we can do with the current state of the system, so I should better get informed :).

**Comment by bgruening** [comment]
>> Different number of columns, different headers/comment lines. Thinking about it I don't know what is similar between them ;)

>Isn't that what metadata is good for?

Are we talking about a new file type here? Shouldn't be a file type as strictly defined as possible?
What do you gain from a new file type that has no defined number of columns, no definition of header/comments over the already existing tabular format?

>> featureCount is even worse, as it does not mark the comment line with # or similar symbols. 
So we need to recognise Geneid 1:, which is not really unique. Also please consider what happens if this identifier is changing between featureCounts versions, for example to Gene-ID 1:. You need to have a new data type to detect this. Versioned datatypes are currently not supported.

> Well, if this happens, the featureCounts wrapper should introduce a new datatype (like GFF and GFF3 are not exactly the same ... yet on a certain level interoperable). I'm seeing this from the angle of the tool wrapper "explaining" what kind of data it is producing. If tools can register new datatypes, I don't see the harm of having a few hundred different datatypes.

Tools can not register new datatypes. Tools can change metadata (to some degree) of an already existing datatype. All feature count tools are producing files that are tab separated, I think this is the most common denominator :).

**Comment by mvdbeek** [comment]
> Tools can not register new datatypes. Tools can change metadata (to some degree) of an already existing datatype. All feature count tools are producing files that are tab separated, I think this is the most common denominator :).

Well, I see the problems in my proposition now. Yet, that would be an interesting approach.

> Are we talking about a new file type here? Shouldn't be a file type as strictly defined as possible?
> What do you gain from a new file type that has no defined number of columns, no definition of header/comments over the already existing tabular format?

I don't really now how to express this well, I'll just called it a datatype, even if that may not be a datatype in the most commonly used sense. The idea would be to have a datatype that can have a set of metadata associated to it. This metadata would include the number of samples (1 or more), the feature that is being counted (genes, exons, whatever is currently in the first column produced by count tools) and the count-data itself (per sample and feature).
The purpose of this is that tool wrappers that produce counts would set this new datatypes as output format and assign columns and rows of their tabular output data to the correct metadata.
Then the datatype would also take care of the conversion, so that tools that need a header-line in their input receive the correct header line, and tools that need multiple input files (one per sample) would receive this as input.
Let me know if you think this is nonsense. I'll be pretty busy the next weeks, but I could keep this in my inbox.

**Comment by bgruening** [comment]
> I don't really know how to express this well, I'll just called it a datatype, even if that may not be a datatype in the most commonly used sense. The idea would be to have a datatype that can have a set of metadata associated to it. This metadata would include the number of samples (1 or more), the feature that is being counted (genes, exons, whatever is currently in the first column produced by count tools) and the count-data itself (per sample and feature).
The purpose of this is that tool wrappers that produce counts would set this new datatypes as output format and assign columns and rows of their tabular output data to the correct metadata.
Then the datatype would also take care of the conversion, so that tools that need a header-line in their input receive the correct header line, and tools that need multiple input files (one per sample) would receive this as input.
Let me know if you think this is nonsense (honesty appreciated!). I'll be pretty busy the next weeks, but I could keep this in my inbox.

This makes sense and is technically possible already. But do you want to change code in Galaxy (the datatypes) and add new converters and other magic with every new release of such a tool? I don't the this overhead justified. The gain is minimal and only for power users, imho. What I usually do is contacting the upstream project and try to convince them to 'fix' the output format, e.g. the blockbuster output. Less work for us and everyone profits from it in a long run :)

**Comment by yhoogstrate** [comment]
> I see it more like we fitting them to other tools, not Galaxy. We all do the same in R and Python if we import data in dataframes, isn't it?

Thanks this clearly shows me your point of view.

> And tabular is imho defined tab separated file without metadata.

This is stated in Tabular.py:

```
# This is our first line, people seem to like to upload files that have a header line, but do not
# start with '#' (i.e. all column types would then most likely be detected as str).  We will assume
# that the first line is always a header (this was previous behavior - it was always skipped).  When
# the requested skip is None, we only use the data from the first line if we have no other data for
# a column. ... truncated ...
```

> Otherwise we need to define these as comment lines.

+1

From the text from Tabular.py I also see this as the solution for featureCounts. I want to keep the column names because for large cohorts (once I had to do 96 samples) you loose which column belongs to which sample when you download the file. The very first char of the header columns should be a ```#```, which would mark the header line as a comment line. Then DESeq should be written such that it skips comment lines, if it doesn't do this already.

> Why not? It's true we'd need to do this for htseq-count, featureCounts and DEXSeq-counts, but if we decide on a common datatype with common metadata, then we'd only need to map Identifiers and counts in the datatype.

These file formats do not have a clear specification like e.g. SAM and that makes this tough to achieve. The formats are quite similar (tab delimited, columns with numbers) and therefore it is not easy to write an accurate sniffers for them. They also do not have something like %%FEATURECOUNTS-EXPRESSION-TABLE-v1.4.6. Therefore I think it's an overkill (time and efford) to write a file format for each of these tools.

>  I'm a bit vague here, admittedly, but it would be nice if galaxy tools could transparently handle the native dataformats produced by htseq-count, featureCounts and DEXSeq-counts, since the kind of information they provide is the same.

You should blame the tool-wrapper authors (in this case it's me) for not having done this. Still this wouldn't solve the issue, because each next tool in the pipeline (edger, deseq, dexseq, ...) should then have a parser for each possible format.  One format to rule them all would be ideal, but that doesn't exist afaik, and would most likely not be a tabular format either.

> Shouldn't be a file type as strictly defined as possible?

+1

> The purpose of this is that tool wrappers that produce counts would set this new datatypes as output format and assign columns and rows of their tabular output data to the correct metadata. Then the datatype would also take care of the conversion, so that tools that need a header-line in their input receive the correct header line, and tools that need multiple input files (one per sample) would receive this as input.

I am not sure if you see this within galaxy or as public tools (like samtools and vcftools) and implement those in galaxy. I think if you start such stuff it also needs indexed access, binary access API etc. available and write a paper on it, otherwise nobody else will use it and we end up with yet another format https://xkcd.com/927/. Other things missing in the current formats are the method used to count (how to treat overlapping annotations and multi-map reads) and the exact genomic structure of each feature counted; it relates to a GTF file which is not explicitly denoted or included.

> Let me know if you think this is nonsense (honesty appreciated!). I'll be pretty busy the next weeks, but I could keep this in my inbox.

It's not nonsense but it probably is a lot of work! This time could be spend on getting GOSeq working or cairo :P

To me the most logical way to close this issue is to let DESeq understand comment lines and denote it clearly in the ```<help>``` section, because the comment are part of the galaxy specification of a Tabular file. To make other tools (featureCounts) compatible with DESeq we can refer to the specification of a tabular file and the README of DESeq.

**Comment by mvdbeek** [comment]
OK, guys, that's absolutely reasonable, and I guess we'll have to live with some "manual" conversion steps for a while. Which is not a problem. So I am closing the issue.
