### ISSUE TITLE
tool request unimap

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#3622]
This is now recommended for some types of alignments over minimap2 (as mentioned in the latest minimap2 release notes: https://github.com/lh3/minimap2/releases/tag/v2.18).

**Comment by gallardoalba** [comment]
It seems to be considered as not recommended over minimap2 after the 2.19 update.
`
This release represents the most significant algorithmic change since v2.1 in 2017. With features backported from unimap, minimap2 now has similar power to unimap for contig alignment. Unimap will remain an experimental project and is
no longer recommended over minimap2. Sorry for reverting the recommendation in short time.
`
Resource: https://github.com/lh3/minimap2/releases/tag/v2.19

**Comment by bgruening** [comment]
Totally true.
