### ISSUE TITLE
Inconsistent output file format

### ISSUE THREAD

**Issue by mthang** [galaxyproject/tools-iuc#3695]
There is a bug in this wrapper causing the inconsistent output file format. The format is set to "rdata", but the R output is set to "rds" format. 
https://github.com/galaxyproject/tools-iuc/blob/b30f2a9974c569de148c3791d42ff7dc8d9b018c/tools/dexseq/dexseq.xml#L106

**Comment by bernt-matthias** [comment]
Galaxy's `rdata` datatype is synonymous to rds/rda (not sure which of the two.. Maybe even both). I agree that this is unfortunate, but I'm unsure how to solve this.

I tend to say that we change the label.. Also we should change the label to more standard, eg `on_sting: rdata`

**Comment by mthang** [comment]
I am able to use "readRDS" function in R to load the data generated by the dexseq.xml. It means that the dexseq.xml should use rds instead of rdata as the datatype. The Rdata contains all the variable object and etc , but the rds is a single data object.

**Comment by bernt-matthias** [comment]
OK. But galaxy currently only has the rdata datatype: 

https://github.com/galaxyproject/galaxy/blob/97946d0be5809270ee256830c616aea118c13450/lib/galaxy/datatypes/binary.py#L2278

That is it does not differentiate rds and rda.

**Comment by mthang** [comment]
Thank you for sharing this piece of information ! is it possible just update the dexseq.r and leave the code base untouch. For example, just update this saveRDS(res, file = "DEXSeqResults.rds") in the dexseq.r to save(res,file="DEXSeqResults.Rdata").

**Comment by bernt-matthias** [comment]
This is possible, but won't change anything on the Galaxy side. The file extension used in the tool wrapper is completely irrelevant. Also I would prefer to keep using `saveRDS` .. see the help for `save`: 

```
     For saving single R objects, ‘saveRDS()’ is mostly preferable to
     ‘save()’, notably because of the _functional_ nature of
     ‘readRDS()’, as opposed to ‘load()’.
```

**Comment by mthang** [comment]
To be honest, either RDS or RDATA datatype is fine as long as the Galaxy users know which datatype is used. I brought up this issue due to a Galaxy user who was unable to read the "RDATA" using the "load()" function offline. Then, I realized that the dexseq.r output is RDS instead of RDATA, but the current Galaxy wrapper (dexseq.xml) output is RDATA. Therefore, the user used "load()" function to load the data instead of using  readRDS function to import the file into the R environment.

**Comment by neoformit** [comment]
@bernt-matthias Just wanted to add my two cents to this conversation.

I am having similar issues developing an interactive tool which takes an `rds` file as an input. It seems that the datatype`rdata` is **not** truly agnostic to whether the source is of `*.rds` or `*.rda` origin:

![image](https://user-images.githubusercontent.com/42562517/128579551-a7f3c2f9-117e-4ace-a2ef-8682208f58ea.png)

It could be the first time this has been noticed if users would not usually upload an `rds` file (I imagine it would usually be used for tool output?). And I assume it's just the sniffer returning `False` so not a huge technical issue - but it does suggest that the `rdata` datatype was created for handling `rda` files.

While it is still technically possible for me to work with this (I think?), as Mike points out above it is bad for user experience when a tool output is of an "anonymous" format. If I download an `rds` file which Galaxy has named `file.rdata`, how am I supposed to know that I should load it with `readRDS()` instead of `load()`?

Furthermore, if I am a inexperienced R user (which I am) then I might not even know that there is a distinction, so when `load()` fails, I would assume that Galaxy rendered a corrupt file:

```
> obj <- load('file.rdata')

Error in load("file.rdata") :
  bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning messages:
1: In readChar(con, 5L, useBytes = TRUE) :
  truncating string with embedded nuls
2: file ‘file.rdata’ has magic number 'X'
  Use of save versions prior to 2 is deprecated
```

For the tool I am developing I have chosen to use a composite datatype as that represents the input data most accurately, but for the wider issue I think that a new Galaxy datatype for `rds` would clarify things a lot for users and developers? It would then be beneficial (but not necessary) to update tools with `rds` input/output to utilize this new datatype. And of course, it could be implemented in future tool wraps to make the handling of `rda` and `rds` formats more transparent for everyone.

Currently we have a confused party of three in our team:
- Myself (new Galaxy developer)
- Mike (@mthang, Galaxy tool developer)
- Sarah (experienced R user and Galaxy end user)

I look forward to hearing your thoughts!

**Comment by bgruening** [comment]
@neoformit, as I understand it would help if we add an 'rds' datatype as well? And make it more clear to the user? We can do so. You just need to add a similar line as here: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/sample/datatypes_conf.xml.sample#L630 and create a new datatypes class that represents `rds` like https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/datatypes/binary.py#L2305

But let me throw in here one thing that we should consider whenever we deal with rdata or rds. To my understanding (and please correct me if that is wrong) both datatypes are not "secure". Tools producing those datatypes are ok, as long as the use-case is downloading the file and mess around with it - we overall trust our tools. But tools **consuming** rdata/rds is a security concern. rdata/rds can contain arbitrary code afaik, its like `pickle` in the Python world, isn't it? This way a user could upload a specifically crafted rdata/rds object execute it on our servers and maybe delete data, execute other programs .

**Comment by neoformit** [comment]
@bgruening Great, leave it to me and I'll add the `rds` datatype when I have a spare moment. I'll try updating DEXSeq to make use of it and check that the functionality is as expected.

Security - yes that sounds correct, although I believe that an exception is made for interactive tools (which I am working on currently) since they run in a Docker container in an isolated environment. In RStudio, for example, the user can of course enter whatever arbitrary code they like. But if you have anything to add to my understanding here (or know of anyone I should ask) I would be very glad to hear it.

**Comment by bgruening** [comment]
@neoformit yes this is true, ITs are less problematic. Thanks for working on this!
