### ISSUE TITLE
script to update all downloadables in TS with sha256sum

### ISSUE THREAD

**Issue by martenson** [galaxyproject/tools-iuc#425]
alternatively we can make @galaxybot do this for us and have him commit the sha256sum alone (homebrew bot does something similar I think)

**Comment by erasche** [comment]
Will reply in a bit I've been doing manually since adding to CPC

**Comment by erasche** [comment]
Okay, I'm :-1: on this with the following rationale:

sha256sums are there to ensure that the software the user is getting is what the author expects them to get. The author writing the package needs to be specifying that hash when they add packages to the CPC, not having this done automatically for them by a bot. 

If it is, they'll say "sure that matches" without even checking. We *need* the person who is familiar with the software to attest that "Yes, this is exactly what I intended to happen."

I promise I'm going to finish the PR tonight, I need to rebase it some more, and fix more urls, but I have a PR which adds sha256sums to all packages in tools-iuc. After that I'll add linting support to planemo, checking for their presence.

**Comment by erasche** [comment]
If you have a compelling use case where you believe that @galaxybot should be doing this, I'm open to listening to it :) I don't mean to shoot down an idea that would automate things and save us time, but I believe there's a reason we should be doing this manually.

**Comment by bgruening** [comment]
@erasche you are correct. But honestly, do you check every tarball manually? I don't. I think this should be (to some degree) part of check.py. 
For me the checksum is more to prevent other attacks after the initial upload or during download.

**Comment by martenson** [comment]
@erasche I would prefer to not spend Galaxy's time - or IUC's - to go through every revision of every TS package/recipe and manually check the downloadables that are being fetched. If you try to be perfect you would have to probably do an audit of the whole source to make sure it is not malicious.
It is great way onward - to check every new package - but I am afraid the choice _here_ is whether to add automatic checksums for past software or not do anything.

**Comment by erasche** [comment]
@bgruening I've been doing spot checks on the packages I've been adding to the CPC, "does this look like it is supposed to". By `check.py` which script are you referring to?

> For me the checksum is more to prevent other attacks after the initial upload or during download.

yep. and to spot changed packages/have them "break" during install in a clearer + safer ways (i.e. we're not trying to run python on an HTML 404 page instead of the python script we intended to download)

@martenson 

> I would prefer to not spend Galaxy's time - or IUC's - to go through every revision of every TS package/recipe and manually check the downloadables that are being fetched. 

I'm not suggesting that. I'm just actually looking at the things that are added to the CPC to make sure they look like what they're supposed to. I'm basically done adding sha256s to tools-iuc, tools-devteam will be very easy to do after this since most of that stuff is already in the CPC.

> If you try to be perfect you would have to probably do an audit of the whole source to make sure it is not malicious.

Yeah, that's just not possible to do, and not what I'm trying to accomplish here. I'm making a best-effort attempt to say "this downloadable looks like what the author probably intended to be downloaded" when adding to the CPC (and by extension, all of the IUC's packages).

> It is great way onward - to check every new package - but I am afraid the choice here is whether to add automatic checksums for past software or not do anything.

So are you suggesting that you wish to modify ALL packages to automatically insert a checksum if it is missing? That seems... aggressive, and was also completely unclear from the original post. That's a very different idea and one I'm definitely more open to.

**Comment by martenson** [comment]
>So are you suggesting that you wish to modify ALL packages to automatically insert a checksum if it is missing?
Yes, for every download. For more security & reproducibility.

**Comment by bgruening** [comment]
> @bgruening I've been doing spot checks on the packages I've been adding to the CPC, "does this look like it is supposed to". By `check.py` which script are you referring to?

https://github.com/erasche/community-package-cache/blob/master/bin/check.py
I would check the content via travis/jenkins as good as possible. 
* no files larger than ...
* only small or no movies, 
* ClamAV check?
* ...

> So are you suggesting that you wish to modify ALL packages to automatically insert a checksum if it is missing?

I also thought this is the question here :)

**Comment by erasche** [comment]
@martenson okay, that yeah, definitely wasn't clear.

I think that implementation belongs not in Galaxybot/IUC, but in the toolshed itself.

@bgruening uhh yes, those are nice, but that's a separate topic and mostly for when we get ready to use the CPC in production, not while it's still under one benevolent dictator who is approving the PRs to it.

**Comment by erasche** [comment]
@martenson I'm closing this and will re-open it against the Galaxy codebase since that's the only place that code makes sense to run.

**Comment by erasche** [comment]
Moved to https://github.com/galaxyproject/galaxy/issues/1187
