### ISSUE TITLE
IUC Contribution Fest - Improve QIIME Tool Generator and Tools

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#426]
as proposed by @lparsons we will also try to work in QIIME during our 2nd IUC Contribution Fest.
This issue will keep track of all QIIME related development.
For more information about the Codefest and the initial discussion please see https://github.com/galaxyproject/tools-iuc/issues/299

xref: http://dev.list.galaxyproject.org/QIIME-tools-for-Galaxy-WIP-call-for-collaborators-td4668035.html

* [ ] datatypes
* [ ] evaluate the usage of a data manager
* [ ] fix planemo lint issues
* [ ] fix dataset collection integration
* [ ] improve usability
* [ ] prepare some workflows to ship with the ToolShed and to demonstrate our achievements 

ping @lparsons and @pjbriggs

**Comment by lleroi** [comment]
Hi everyone, 

I setted up the [454 qiime workflow](http://qiime.org/tutorials/tutorial.html) on a private Galaxy instance.
I used the ``qiime-galaxy`` scripts to generate the wrappers. For the scripts used in the 454 workflow, I deleted the tgz in/output option and choose which options can be specified on the xml wrappers.

For the ``pick_otus.py`` wrapper, I modified how the clustering options are displayed (eg. swarm options are displayed if ``swarm`` is selected for the clustering, uclust options displayed if ``uclust`` is selected etc...)
I selected 6 of the 12 clustering methods (those are the most interesting for our team) : ``uclust``, ``uclust_ref``, ``swarm``, ``usearch``, ``usearch_ref`` and ``sumaclust``.

What do you think about it ? 

If it's ok for you, I will make a fork, create a branch, commit the changes and make a pull request.

**Comment by bgruening** [comment]
@lleroi I think this is a good start. I will create an empy branch. Can you create your PR against this one here: https://github.com/galaxyproject/tools-iuc/pull/431

I guess we can work all together on this branch then.
Thanks a lot!

**Comment by lparsons** [comment]
Good start. Before we get too far, do we want to:

1. Update individual wrappers, starting from the output of the  [Qiime Galaxy tool generation scripts](https://github.com/qiime/qiime-galaxy)
2. Update the [Qiime Galaxy tool generation scripts](https://github.com/qiime/qiime-galaxy)

Personally, I prefer option 1 as I think it's more straightforward and will lead more quickly to some useful tools.

In general, the tools created by the Qiime Galaxy scripts package up all the output into tar files, which are not very usable in Galaxy. One option that I've started working on is to split out the most relevant output files from scripts and package up the rest. Another option would be to write wrappers that take the tar files as input. I'm less in favor of that, though it has some appeal since the qiime tools tend to expect the user to run everything in the same directory, reading and writing output to various subdirectories.

**Comment by bgruening** [comment]
@lparsons I trust your decision here and accept whatever comes first :)

**Comment by lparsons** [comment]
I'd like to get an [Illlumina qiime workflow](http://nbviewer.ipython.org/github/biocore/qiime/blob/1.9.1/examples/ipynb/illumina_overview_tutorial.ipynb) working in Galaxy.

I've started on this at https://github.com/lparsons/galaxy_tools/blob/qiime/tools/qiime1.9.0/.  As I see it, this requires the following things:

1. Tool to handle barcode splitting that will label the the reads instead of splitting into individual files (this seems to be the expected input for many Qiime tools). See [split_libraries_fastq.py](http://qiime.org/scripts/split_libraries_fastq.html) and my [updated split_libraries_fastq wrapper](https://github.com/lparsons/galaxy_tools/blob/qiime/tools/qiime1.9.0/split_libraries_fastq.xml)

2. Fix [count_seqs.py](http://qiime.org/scripts/count_seqs.html) wrapper to avoid tarring up the output. [Updated count_seqs.py wrapper](https://github.com/lparsons/galaxy_tools/blob/qiime/tools/qiime1.9.0/count_seqs.xml) 

3. Update pick_open_reference_otus.py wrapper

4. Biom datatype (@jchilton working on this?)

5. Biom tools (for biom summarize-table)

6. Update wrapper for core_diversity_analyses.py

7. Update wrapper for make_emperor.py

The updates to the wrappers have so far involved changing output file handling to allow individual output files to be in history, adding tests and test data, general clearnup (macros, citations, etc.) to make sure they all pass planemo linting and tests run.

**Comment by lparsons** [comment]
Great, I have a few things that I need to take care of first, but when I get back to this, I'll prepare a PR against this branch so we can start coordinating.

I briefly checked in on IRC, is there a Google Hangout as well?

**Comment by blankenberg** [comment]
@lparsons hangout at https://hangouts.google.com/hangouts/_/iems2ffkpd4s7cyjoq4mi3hgwma

**Comment by lparsons** [comment]
Initial work in my fork:https://github.com/lparsons/tools-iuc/tree/illumina-workflow-tools. Let me know if it would help to submit PR now, otherwise I'll continue working here.

**Comment by lparsons** [comment]
One piece of work that is somewhat isolated, and would be very useful, is to get an intial implementation of biom tools (e.g. summarize-table). Minimally:

- [ ] create a repository dependency for biom tools (package_ biom-format_x.x), or is this already taken care of in galaxyproject/galaxy#950?
- [ ] Tool wrapper for summarize-table (http://biom-format.org/documentation/summarizing_biom_tables.html)

**Comment by bgruening** [comment]
@lparsons if you don't mind please submit a PR. So we can coordinate the effort here for tomorrow.
@yvanlebras regarding biom tools. I know he is using them already in his workflow so we can probably include his wrapper.

**Comment by lparsons** [comment]
@bgruening Don't mind at all. PR submitted. Will look into @yvanlebras biom wrappers tomorrow, thanks for the tip.

**Comment by pjbriggs** [comment]
@lparsons I've started looking at updating your pick_open_reference_otus.py wrapper, along the lines of what it looks like you've already done for count_seqs.py. Please let me know if you're already working on this.

**Comment by lparsons** [comment]
@pjbriggs I barely started with that yesterday and got pulled away. It'd be great if you could work on that and incorporate the use of biom datatype for the output. I'll see what's going on with biom tools from @yvanlebras. Thanks!

**Comment by pjbriggs** [comment]
@lparsons I've made a little progress with the pick_open_reference_otus.py wrapper but have run out of time today to do any more. So I've submitted a PR in case you have time to look at it and make suggestions/criticisms (in particular any advice on which outputs should be captured in the history). I'll try and do more tomorrow, but hope this is useful for now.

**Comment by bgruening** [comment]
@lleroi @pjbriggs @lparsons I guess we need to adopt all tools to macros and execute a few sed commands on top of that. 
The generator produces not so nice results.

**Comment by lparsons** [comment]
There are a LOT of tools (and not all of them are that useful). Also, many of the tools have very complicated output (many files, etc.) so it's a bit more than using sed. That's why I decided to focus on a workflow first, to get something useful. Then, using those tools as a template, start updating wrappers for other tools.

**Comment by bgruening** [comment]
Qiime is worked on in https://github.com/galaxyproject/tools-iuc/pull/431
