### ISSUE TITLE
Medaka consensus pipeline error

### ISSUE THREAD

**Issue by zmeel** [galaxyproject/tools-iuc#5233]
I'm running a Galaxy instance on a Ubuntu server. I have a workflow that runs fine on usegalaxy.eu but when I run it on my own server the medaka consensus tool always give an error:
 `{ "code_desc": "", "desc": "Fatal error: Exit code 126 ()", "error_level": 3, "exit_code": 126, "type": "exit_code" }.`

I have installed most tools with conda: 
`conda create -y --quiet --override-channels --channel conda-forge --channel bioconda --channel defaults --name __medaka@1.7.2 medaka=1.7.2`
Galaxy sees the medaka tool and also shows that all dependencies are resolved. However, when I run the workflow it gives the above error. I would appreciate any help to resolve this issue

**Comment by wm75** [comment]
Hard to diagnose this problem without having access to the machine where it occurs, but exit code 126 usually means "command not executable".
medaka is tool that's notoriously difficult to install with conda since the dependencies are hard to resolve and conda often gives up eventually. So it could be that your conda env doesn't have a successfully installed tool, which Galaxy only finds out at run time.
Have you checked whether you can execute the tool from the command line? Or have you tried to conda list the contents of the env? If this is really a problem with the conda install, you may want to give mamba a try because it's much better and faster at resolving complex envs.

**Comment by zmeel** [comment]
I reinstalled the medaka tool with mamba and now everything is working fine! Thanks...

**Comment by wm75** [comment]
Now that is weird :(

> I reran the medaka tool after I reinstalled prokka with mamba.

As long as you're keeping those envs separate, that shouldn't matter. Do you get any more detailed output when running medaka from the same env through command line?

**Comment by wm75** [comment]
Ah, just saw your parallel question on the help forum: https://help.galaxyproject.org/t/local-workflow-with-medaka-fails-with-error/9782 and there you're saying that you're copying the conda env over to Galaxy, which might cause all kinds of issues with paths.
I guess the proper way to do this is using the `--prefix` option with conda create, then activate that environment and mamba install medaka into it, though I haven't tried it myself.
