### ISSUE TITLE
Wrapper bug with get_species_taxids

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/tools-iuc#5643]
See Xref for details and test histories at both ORG and EU https://github.com/galaxyproject/usegalaxy-tools/issues/653

Wrapper bug at both servers in toolshed.g2.bx.psu.edu/repos/devteam/ncbi_blast_plus/get_species_taxids/2.14.1+galaxy0

The name query is being sent as a taxids query, and fails with this. Seems the "name versus taxid" toggle has problems?
> /data/jwd05e/main/064/491/64491173/tool_script.sh: line 27: [: too many arguments
> Taxonomy ID not found

**Comment by bernt-matthias** [comment]
Wrong repo :) Tool is here https://github.com/peterjc/galaxy_blast/blob/master/tools/ncbi_blast_plus/get_species_taxids.xml

> The name query is being sent as a taxids query

This is intended. 

The script gets first the taxids for the names https://github.com/peterjc/galaxy_blast/blob/d63652a431c24fa35c5535784b8d466c11bbab04/tools/ncbi_blast_plus/get_species_taxids.xml#L10

And then gets the taxids in the subtree https://github.com/peterjc/galaxy_blast/blob/d63652a431c24fa35c5535784b8d466c11bbab04/tools/ncbi_blast_plus/get_species_taxids.xml#L16

Does this make sense to you?

Even stranger is that we even have a test case identical to your shared job: https://github.com/peterjc/galaxy_blast/blob/d63652a431c24fa35c5535784b8d466c11bbab04/tools/ncbi_blast_plus/get_species_taxids.xml#L49. So I guess the error is caused by a temporary problem at NCBI. 

Nevertheless, I improved the shell syntax a bit and hope that the tool is now a bit more robust.

https://github.com/peterjc/galaxy_blast/pull/161

**Comment by bernt-matthias** [comment]
https://github.com/peterjc/galaxy_blast/pull/161https://github.com/peterjc/galaxy_blast/pull/161
