### ISSUE TITLE
Numpy 1.9 install issue

### ISSUE THREAD

**Issue by Slugger70** [galaxyproject/tools-iuc#697]
Hi there,

Whilst installing JBrowse from the toolshed (main), I kept getting failure to install some of the dependencies. It looks as though there is something wrong with easy_install in the python dependency for JBrowse.

It occurs for 4 of the deps for JBrowse: Numpy 1.9, pyyaml, biogff and another I can't remember at the moment. A screenshot of the error appears below.

![screen shot 2016-03-30 at 11 08 03 am](https://cloud.githubusercontent.com/assets/1740254/14132224/2ded7930-f68f-11e5-9a38-8d5a78d3f0ba.png)

I thought if I re-ran the install from the test tool shed I would get fresh everything (as I have nothing installed from the test tool shed) but the same thing occurred. 

The only way I could get Numpy to install was to manually set up the environment as per the INSTALLATION.log file and then run python ez_setup.py (to fix setup_tools). Numpy will then install correctly. 

However, now biopython will not recognise the numpy install and refuses to work. Grrr. Even after reinstallation of biopython.

![screen shot 2016-03-30 at 3 57 16 pm](https://cloud.githubusercontent.com/assets/1740254/14132310/2980d24c-f690-11e5-9821-7666f4369975.png)

Any ideas what could be going on?

**Comment by pjbriggs** [comment]
@Slugger70 the second problem (i.e. biopython install failing due to missing numpy, even though the package does appear to be installed) looks very much like a problem we've encountered with `package_biopython_1_66`.

In that case the problem is actually with the underlying `package_numpy_1_9`, so reinstallation won't help (as you observed). I've submitted a pull request (PR #739) for `package_numpy_1_9` which I believe should address this problem if it's applied and uploaded to the toolshed.

**Comment by mictadlo** [comment]
@bgruening DeepTools failed from TestTooshed, because of similar problem with `package_python_2_7_numpy_1_9`:

Browse tool dependency numpy installation directory
Tool shed repository:
package_python_2_7_numpy_1_9
Tool shed repository changeset revision:
fe0870696ca7
Tool dependency status:
Error
Tool dependency installation error:
usage: easy_install [options] requirement_or_url ... or: easy_install --help error: invalid command 'easy_install'
Tool dependency installation directory:
/mnt/galaxy/tools/numpy/1.9/iuc/package_python_2_7_numpy_1_9/fe0870696ca7
Contents:
numpy
INSTALLATION.log
env.sh

#############################################
PATH=/mnt/galaxy/tools/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d/bin:$PATH; export PATH
PYTHONPATH=/mnt/galaxy/tools/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d:$PYTHONPATH; export PYTHONPATH
PYTHONPATH=/mnt/galaxy/tools/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d/lib:$PYTHONPATH; export PYTHONPATH
PYTHONPATH=/mnt/galaxy/tools/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d/lib/python2.7:$PYTHONPATH; export PYTHONPATH
PYTHONPATH=/mnt/galaxy/tools/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d/lib/python2.7/site-packages:$PYTHONPATH; export PYTHONPATH
PYTHONHOME=/mnt/galaxy/tools/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d; export PYTHONHOME
PKG_CONFIG_PATH=/mnt/galaxy/tools/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d/lib/pkgconfig:$PKG_CONFIG_PATH; export PKG_CONFIG_PATH
PYTHON_ROOT_DIR=/mnt/galaxy/tools/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d:$PYTHON_ROOT_DIR; export PYTHON_ROOT_DIR
LD_LIBRARY_PATH=/mnt/galaxy/tools/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d/lib:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH
C_INCLUDE_PATH=/mnt/galaxy/tools/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d/include/python2.7:$C_INCLUDE_PATH; export C_INCLUDE_PATH
CPLUS_INCLUDE_PATH=/mnt/galaxy/tools/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d/include/python2.7:$CPLUS_INCLUDE_PATH; export CPLUS_INCLUDE_PATH
PATH=$PATH:$PYTHONHOME/bin; export PATH;
                                export PYTHONPATH=$PYTHONPATH:/mnt/galaxy/tools/numpy/1.9/iuc/package_python_2_7_numpy_1_9/fe0870696ca7;
                                easy_install --no-deps --install-dir /mnt/galaxy/tools/numpy/1.9/iuc/package_python_2_7_numpy_1_9/fe0870696ca7 --script-dir /mnt/galaxy/tools/numpy/1.9/iuc/package_python_2_7_numpy_1_9/fe0870696ca7/bin numpy_1.9p1_src_all.tar.gz
                            
STDOUT

#############################################

#############################################
PATH=/mnt/galaxy/tools/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d/bin:$PATH; export PATH
PYTHONPATH=/mnt/galaxy/tools/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d:$PYTHONPATH; export PYTHONPATH
PYTHONPATH=/mnt/galaxy/tools/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d/lib:$PYTHONPATH; export PYTHONPATH
PYTHONPATH=/mnt/galaxy/tools/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d/lib/python2.7:$PYTHONPATH; export PYTHONPATH
PYTHONPATH=/mnt/galaxy/tools/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d/lib/python2.7/site-packages:$PYTHONPATH; export PYTHONPATH
PYTHONHOME=/mnt/galaxy/tools/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d; export PYTHONHOME
PKG_CONFIG_PATH=/mnt/galaxy/tools/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d/lib/pkgconfig:$PKG_CONFIG_PATH; export PKG_CONFIG_PATH
PYTHON_ROOT_DIR=/mnt/galaxy/tools/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d:$PYTHON_ROOT_DIR; export PYTHON_ROOT_DIR
LD_LIBRARY_PATH=/mnt/galaxy/tools/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d/lib:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH
C_INCLUDE_PATH=/mnt/galaxy/tools/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d/include/python2.7:$C_INCLUDE_PATH; export C_INCLUDE_PATH
CPLUS_INCLUDE_PATH=/mnt/galaxy/tools/python/2.7.10/iuc/package_python_2_7_10/a28e3c30828d/include/python2.7:$CPLUS_INCLUDE_PATH; export CPLUS_INCLUDE_PATH
PATH=$PATH:$PYTHONHOME/bin; export PATH;
                                export PYTHONPATH=$PYTHONPATH:/mnt/galaxy/tools/numpy/1.9/iuc/package_python_2_7_numpy_1_9/fe0870696ca7;
                                easy_install --no-deps --install-dir /mnt/galaxy/tools/numpy/1.9/iuc/package_python_2_7_numpy_1_9/fe0870696ca7 --script-dir /mnt/galaxy/tools/numpy/1.9/iuc/package_python_2_7_numpy_1_9/fe0870696ca7/bin numpy_1.9p1_src_all.tar.gz
                            
STDERR
usage: easy_install [options] requirement_or_url ...
   or: easy_install --help

error: invalid command 'easy_install'
#############################################

How is it possible to fix it?

Thank you in advance.

Mic

**Comment by yhoogstrate** [comment]
I don't know for sure but should it depend on `package_ez_setup_0_9`?

@mictadlo Could you create a clone of the repository under your name and test if this works out for you with the following `tool_dependencies.xml`:

```
<?xml version="1.0"?>
<tool_dependency>
    <package name="atlas" version="3.10.2">
        <repository name="package_atlas_3_10" owner="iuc" prior_installation_required="True" />
    </package>
    
    <package name="ez_setup" version="0.9">
        <repository name="package_ez_setup_0_9" owner="iuc" prior_installation_required="True" />
    </package>
    
    <package name="python" version="2.7.10">
        <repository name="package_python_2_7_10" owner="iuc" prior_installation_required="True" />
    </package>
    
        <package name="numpy" version="1.9">
            <install version="1.0">
                <actions>
                    <action type="setup_python_environment">
                        <repository name="package_ez_setup_0_9" owner="iuc">
                            <package name="ez_setup" version="0.9" />
                        </repository>

                       <repository name="package_python_2_7_10" owner="iuc">
                           <package name="python" version="2.7.10" />
                       </repository>
                        <repository name="package_atlas_3_10" owner="iuc">
                            <package name="atlas" version="3.10.2" />
                        </repository>
                        <package sha256sum="9753003ab7c489968eb260e5460556fd7d533a8e11a9d5326e0995bd1aa21318">https://depot.galaxyproject.org/software/numpy/numpy_1.9p1_src_all.tar.gz</package>
                    </action>
                    <action type="set_environment">
                        <environment_variable action="prepend_to" name="PYTHONPATH">$INSTALL_DIR</environment_variable>
                        <environment_variable action="prepend_to" name="PATH">$INSTALL_DIR/bin</environment_variable>
                        <environment_variable action="prepend_to" name="LD_LIBRARY_PATH">$ENV[ATLAS_LIB_DIR]</environment_variable>
                        <environment_variable action="set_to" name="PYTHONPATH_NUMPY">$INSTALL_DIR</environment_variable>
                        <environment_variable action="prepend_to" name="LD_LIBRARY_PATH">$ENV[ATLAS_LIB_DIR]/atlas</environment_variable>
                        <environment_variable action="set_to" name="PATH_NUMPY">$INSTALL_DIR/bin</environment_variable>
                        <environment_variable action="set_to" name="NUMPY_ROOT_DIR">$INSTALL_DIR</environment_variable>
                    </action>
                </actions>
            </install>
            <readme>Compiling numpy requires a C and Fortran compiler (typically gcc and gfortran). The PYTHONPATH for numpy can be accessed through PYTHONPATH_NUMPY and the binaries with PATH_NUMPY.</readme>
        </package>
</tool_dependency>
```

**Comment by mictadlo** [comment]
@yhoogstrate How do I create a clone of the repository under my name and test the above file?

**Comment by yhoogstrate** [comment]
Just Go to the website of the testtoolshed and create it via the web interface. You only have to upload one file So IT should Be Easy. If you are More experienced with Galaxy you could use planemo instead. In that Case you need to update the `owner` in the file `.shed.yml` to your username.

**Comment by mictadlo** [comment]
@yhoogstrate I loged in to testtoolshed and found only `repository_dependencies.xml`  ( https://mictadlo@testtoolshed.g2.bx.psu.edu/repos/bgruening/suite_deeptools/file/cf8e531b309f/repository_dependencies.xml ), but I could not find any upload link.

I would be happy to try planemo, but I have not use it before. By any chance do you have any links to (video) tutorials?
