### ISSUE TITLE
bedtools - Genome file

### ISSUE THREAD

**Issue by MoHeydarian** [galaxyproject/tools-iuc#720]
The bedTools tools were updated recently in Galaxy with some great additions. Some of these updated tools require a 'Genome file', which is a file containing the size of the chromosomes of your reference genome. 
Since the reference genome is associated with files input to bedTools does it make sense to have the user input the 'Genome file' when the same information is likely available in the inner workings of Galaxy? Having the user create and recall the 'Genome file' seems like an opportunity to introduce unnecessary errors.

**Comment by MoHeydarian** [comment]
Bump. 

This is still causing confusion.

**Comment by yhoogstrate** [comment]
Hi @MoHeydarian ,

I think this requires to have a `*.loc` file containing entries of `*.len` files in Galaxy's tool-data directory. Now *.len files are stored in Galaxy in `galaxy/tool-data/shared/ucsc/chrom` but are not tracable via a loc file and thus not for tools (or in a way I am not aware of). It think having this file would simplify fixing this.

Could you help us a bit on this by making a small contribution to Galaxy to add such a file?

**Comment by blankenberg** [comment]
Take a look at the `__dbkeys__` data table.

**Comment by yhoogstrate** [comment]
@blankenberg the `__dbkeys__` table seems absent in `app.tool_data_tables` while it is present in `app.genome_builds.get_chrom_info($dbkey)`. This way I can't use it with `<options from_data_table="__dbkey_" />`. Do you have an example?

**Comment by bwlang** [comment]
i handled this for bam file inputs by examining headers of the bam...
see https://github.com/galaxyproject/tools-iuc/blob/c72d58cbe6a99bc8f9fde26fdde45b0c222890df/tools/bedtools/coverageBed.xml#L29

though i'm about to fix an issue with that (can't deal with : containing contig names)

**Comment by jennaj** [comment]
Hi - BedTools are still accessing the wrong data table to get all of the currently installed genomes/len data. 

Latest version in MTS: https://toolshed.g2.bx.psu.edu/view/iuc/bedtools/db1841942d2b

Example: FisherBed -- for _Genome file > Locally installed Genome File_ it is pulling data from __dbkeys__ which on cvmfs only contains two special curated genomes, not everything from all_fasta*. **This impacts all of the usegalaxy.* servers.** Org and Org.au have the same content, Eu has different content (might not be using cvmfs?). To see what is going on, go into _Admin > Data tables_ and compare the content of the __dbkeys__ files to the genomes available in this tool.

I'm not sure of the correct fix -- is it possible that __dbkeys__ is being populated incorrectly? @blankenberg, could you take a look?

@bgruening @natefoo @yhoogstrate

**Comment by natefoo** [comment]
The `__dbkeys__` table on Main/CVMFS would be populated with the data_manager_fetch_genome_dbkeys_all_fasta DM on test-datamanager and then by running the procedure [here](https://github.com/galaxyproject/usegalaxy-playbook/wiki/Publishing-Indexes-to-Main).

If there's supposed to be some means whereby the UCSC builds (not DM-updated) are supposed to be automatically added to `__dbkeys__` I'm not aware of it. Otherwise we'd need to do it in [the script](http://datacache.galaxyproject.org/managed/bin/ucsc_update.sh) that does the UCSC build updates (which, incidentally, is not working right due to some weird cron/CVMFS interaction, but that is another matter).

**Comment by jennaj** [comment]
Shouldn't all genomes with a .len available be in __dbkeys__ if tools are using it? Otherwise, what is available is a subset of the available data. So that would include all the UCSC genomes (whether fetched/indexed or not for other tools since we pull that data in) plus any other genome fetched/indexed.

Example: Yesterday a user wanted to run that tool with mm10 and dm6. Neither are included but do have .len data available. The two genomes on main in the __dbkeys__ tables were genomes that were indexed using a fasta from the history (only). None that were created other ways are included.

**Comment by natefoo** [comment]
I don't know, I am not aware of the history of `__dbkeys__` or what tools use it, and why they use it vs. `all_fasta`. However, since the data_manager_fetch_genome_dbkeys_all_fasta DM appears to be designed to update both tables, it seems reasonable that our older sequences that have lengths available should be added to `__dbkeys__`.

For pre-DM sequences, most (all) of these should already have lengths in `/cvmfs/data.galaxyproject.org/byhand/lengths`.

For sequences fetched with the non-`__dbkey__`-aware data_manager_fetch_genome_all_fasta, it looks like we'd need to generate lengths.

Does this sound correct? I can do the necessary table/location changes if so.

**Comment by natefoo** [comment]
Turns out the UCSC update script already fetches [all the lengths](http://datacache.galaxyproject.org/managed/len/ucsc/). So these just need to be added to a location file and the `__dbkeys__` data table.

**Comment by natefoo** [comment]
Ok, all the UCSC builds are now in `__dbkeys__` on usegalaxy.org.

**Comment by bgruening** [comment]
@natefoo which file needs to be updated? Do you have it somewhere? Thanks.

**Comment by natefoo** [comment]
If you use `/cvmfs/data.galaxyproject.org/managed/location/tool_data_table_conf.xml`, then you'll automatically get it the next time your data tables are reloaded and/or you restart.

**Comment by jennaj** [comment]
Populated and works at ORG now, thanks!

**Comment by jennaj** [comment]
Looks like EU is still being updated. Not sure if they use that cvmfs data -- GUI genome content differs.

AU would also benefit from the data table update/restart. Pretty sure are using cvmfs from the GUI genome content (this suite & across other tools). ping @Slugger70

**Comment by Slugger70** [comment]
We'll be restarting AU tonight our time. Thanks for the heads up @jennaj

**Comment by bgruening** [comment]
We are not using CVMFS yet, its next on our list.

**Comment by martenson** [comment]
@jennaj I don't understand what is being asked of me.

**Comment by jennaj** [comment]
We solved the core issue (and dependent issues) last week. All genomes are now included at both Test and Main for this tool. Also, the new data was fixed up and published to cvmfs. 

This issue ticket can be closed out as fixed.
