### ISSUE TITLE
Star data manager

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/tools-iuc#751]
I recognised that our star data manager is not in the TS. https://github.com/galaxyproject/tools-iuc/blob/master/data_managers/data_manager_star_index_builder/data_manager/rnastar_index_builder.xml

@mvdbeek @yhoogstrate how are you building you indices. Should be upload/update it?

**Comment by yhoogstrate** [comment]
I think it's good to have a data manager for star. The indices are really big (9* size of fasta). That's probably also the reason nobody is hosting them, or at least I am not aware of that. So it always comes down to generating them yourself.

I am not a fan of using python files as wrappers while you could do the same in cheetah. Do you want this to be changed?

**Comment by bgruening** [comment]
@yhoogstrate as you like. I was more wondering if this data manager is working and why it is not in the MTS. If you can upgrade it and push it into the TSs this would be great!

**Comment by yhoogstrate** [comment]
I have been looking into the data manager and it is not ready yet.

 - [ ] Depends on wrong STAR package (incorrect owner)
 - [ ] Has no .shed.yml so can not be automatically deployed
 - [ ] The data manager saves a symlink to a fasta file within the ref-index directory, while the STAR wrapper expects the path to the directory
 - [ ] Column names in 'tool-data/rnastar_index.loc.sample' are inconsistent with the names in 'tool_data_table_conf.xml.sample'
 - [ ] all_fasta.loc.sample is outdated. I am thinking of creating a "./tool-data" directory in the root directory of the tools-iuc repository, and symlink all `all_fasta.loc.sample` files to that one because we're now maintaining multiple not-identical copies of the same file

**Comment by yhoogstrate** [comment]
This issue has been resolved - https://github.com/galaxyproject/tools-iuc/pull/1207
