### ISSUE TITLE
DeSeq2 Fails to install local galaxy

### ISSUE THREAD

**Issue by djevo1** [galaxyproject/tools-iuc#900]
Loading Deseq2 from toolshed produces and error and only gives this output as an error.

`if [ -f /home/galaxy/galaxy/tool_dep/deseq2/1.8.2/iuc/package_deseq2_1_8_2/623321e04b2d/env.sh ] ; then . /home/galaxy/galaxy/tool_dep/deseq2/1.8.2/iuc/package_deseq2_1_8_2/623321e04b2d/env.sh ; fi`

**Comment by yhoogstrate** [comment]
Dear @djevo1,

Thanks for reporting! This is not a general error message but part of an include script galaxy uses internally to run DESeq2. I need more information in order to help you. Could you please also report what information is given when you run DESeq2 with some data, go to the (red) history item, expand it, press the (i)-icon and press *stderr*?

all best,

Youri
